### PR TITLE
[VKCI-219] [common-core] Make RDE.state type as a custom string type

### PR DESCRIPTION
**Pull request by ymo24**
* [common-core] Make RDE.state type as a custom string type

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/297)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by lzichong — APPROVED** [review]
:lgtm:, not directly related to the PR, but could you run `go vet` and see if there are any outstanding issues that needs to be fixed in the code?

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/297#-:-Nfm4S8SE-TSjb8r5Xsx:b-8w0xqj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ymo24)

**Review by lzichong — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ymo24)

**Review by ltimothy7 — APPROVED** [review]

**Review by arunmk — APPROVED** [review]
:lgtm: 
One small but important change needed (rename of file)

> Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/297#-:-Nfr94YC9VDzHu-ep6dE:b-vsyzuk)* status: all files reviewed, 1 unresolved discussion (waiting on @ymo24)

___
*[`pkg/vcdswaggerclient_37_2/model_defined_entity.go` line 1 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/297#-Nfr8xOM9nFR3ytMZ_wF:-Nfr8xOM9nFR3ytMZ_wG:broc1de) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/25c1156a4a288658c93bf81b51ba4ee6491867d4/pkg/vcdswaggerclient_37_2/model_defined_entity.go#L1)):*
> ```Go
> /*
> ```

Can you rename this file to `model_defined_entity_modified.go` so that we know which files are different from the autogenerated files in the future.

**Pull request merged**
