### PR TITLE
[cherry-pick][VKCI-99] Upgrade golang.org/x package

### PR DESCRIPTION
**Pull request by ymo24**
* upgrade golang.org/x/net to v0.4.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/204)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
Hi Yan
This PR needs to go into branch 1.3.z instead of main. Please ensure that the PR is cherry-pick'd using the cherry-pick command for the commit of the PR in main branch

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/204#-:-NKyV2T6CL3ANkn5vVq1:b-ug8lsc)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @lzichong)

**Review by lzichong — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/204#-:-NKygJWBDdbPdEpV7G9K:bg7igkv)* status: 4 of 14 files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/204)* status: 4 of 14 files reviewed, all discussions resolved

**Review by ymo24 — COMMENTED** [review]
thanks

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/204#-:-NKyjBNq1Vahhpxb_L3r:b-k73z76)* status: 4 of 14 files reviewed, all discussions resolved (waiting on @ltimothy7 and @lzichong)

**Pull request merged**
