### PR TITLE
Move functions from vcdclient in CAPVCD to vcdsdk in CPI 

### PR DESCRIPTION
**Pull request by Anirudh9794**
ticket: VCDA-3528
Changes:
* Functions specific to CPI are moved to vcdcpiclient package
* Added functions from vcdclient from CAPVCD to vcdsdk in CPI
Testing:
* create docker image using make ccm
* nginx and shapes test

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
:lgtm: (couple of comments to keep track of)

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-:-N166IhA-e_XDyT6T5zy:bm0u1tp)* status: 0 of 28 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/ccm/cloud.go` line 14 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N0qta0HAed70-TM2Nv1:-N0qta0HAed70-TM2Nv2:b-yjplqh) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/ccm/cloud.go#L14)):*
> ```Go
> 	"fmt"
> 	"github.com/vmware/cloud-provider-for-cloud-director/pkg/config"
> 	"github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdcpiclient"
> ```

What is the vcdcpiclient used for?
___
*[`pkg/ccm/loadbalancer.go` line 13 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N164m-RER6NqwT0dROb:-N164m-RER6NqwT0dROc:b-u47fdx) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/ccm/loadbalancer.go#L13)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdcpiclient"
> ```

I suggest renaming it to cpisdk
___
*[`pkg/ccm/loadbalancer.go` line 132 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N163M5z0hmiqfmzyAUi:-N163M5z0hmiqfmzyAUj:bbwuywb) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/ccm/loadbalancer.go#L132)):*
> ```Go
> 		virtualServiceName := fmt.Sprintf("%s-%s", virtualServiceNamePrefix, portName)
> 		externalPort := typeToExternalPort[portName]
> 		cgm, err := vcdcpiclient.NewCpiGatewayManager(ctx, lb.vcdClient, lb.ovdcNetworkName, lb.ipamSubnet, lb.clusterID)
> ```

Aniruddh,

I see that we have two separate gatewaymanagers for CPI and commoncode. It is okay to keep them this way for now as we cannot refactor and reorganize everything at once. Eventually, we need to think about consolidating these. Having separate logic means more maintenance. For example, any fixes in the loadbalancer area need to be patched at two places.

I do understand that we have to solve another problem of RDE updates coming from these methods. RDE updates need to go to different sections depending on the caller. We need to see if that can be safely parameterized.

Please add a TODO somewhere and create a DESIGN jira task detailing the goals and potential proposals.
___
*[`pkg/vcdsdk/defined_entity.go` line 149 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N160uON6dHevD9UpOuS:-N160uON6dHevD9UpOuT:b-vpcgp1) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/vcdsdk/defined_entity.go#L149)):*
> ```Go
> 
> // AddToVCDResourceSet adds a VCDResource to the VCDResourceSet of the component in the RDE
> func (rdeManager *RDEManager) AddToVCDResourceSet(ctx context.Context, component string, resourceType string,
> ```

I assume this method is going to take additional param of "RDE hierarchical path". For example "RDE.status.capvcd.vcdresourceset"? The plan is to do this as another task, right?
___
*[`pkg/vcdsdk/vapp.go` line 516 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N165m4WA33q9TTu3oNB:-N165m4WA33q9TTu3oNC:badk1dh) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/vcdsdk/vapp.go#L516)):*
> ```Go
> // AddNewMultipleVM will create vmNum VMs in parallel, including recompose VApp of all VMs settings,
> // power on VMs and join the cluster with hardcoded script
> func (vdc *VdcManager) AddNewMultipleVM(vapp *govcd.VApp, vmNamePrefix string, vmNum int,
> ```

Please ensure storage profile code (added by Adnan) is retained here. It is relevant in both CPI main and vkp branches. Please track it as separate task if you want to do it as part of another PR

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69)* status: 0 of 28 files reviewed, 5 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`pkg/ccm/cloud.go` line 14 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N0qta0HAed70-TM2Nv1:-N1CH8FL9dx2eHptjOZ3:bq73ryz) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/ccm/cloud.go#L14)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What is the vcdcpiclient used for?
</blockquote></details>

the current implementation of some functions are very specific to CPI.
- CRUD Load Balancer (contains specific RDE based operations).
- Code to add/remove virtual IPs to/from RDEs
These functions are currently kept as part of vcdcpiclient. I will rename the package to cpisdk as discussed offline.

As discussed I have created VCDA-3647 to design changes so that CRUD Load balancer can also be moved to vcdsdk
___
*[`pkg/ccm/loadbalancer.go` line 13 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N164m-RER6NqwT0dROb:-N1CHvwW1lpW1Iunl1SD:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/ccm/loadbalancer.go#L13)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest renaming it to cpisdk
</blockquote></details>

Done.
___
*[`pkg/ccm/loadbalancer.go` line 132 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N163M5z0hmiqfmzyAUi:-N1CI_yu3w9FADveVQet:b-p3x3i) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/ccm/loadbalancer.go#L132)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Aniruddh,

I see that we have two separate gatewaymanagers for CPI and commoncode. It is okay to keep them this way for now as we cannot refactor and reorganize everything at once. Eventually, we need to think about consolidating these. Having separate logic means more maintenance. For example, any fixes in the loadbalancer area need to be patched at two places.

I do understand that we have to solve another problem of RDE updates coming from these methods. RDE updates need to go to different sections depending on the caller. We need to see if that can be safely parameterized.

Please add a TODO somewhere and create a DESIGN jira task detailing the goals and potential proposals.

</blockquote></details>

Added a TODO and created VCDA-3647
___
*[`pkg/vcdsdk/defined_entity.go` line 149 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N160uON6dHevD9UpOuS:-N1CIfph6AjWAUZVqL-H:bj5di1w) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/vcdsdk/defined_entity.go#L149)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I assume this method is going to take additional param of "RDE hierarchical path". For example "RDE.status.capvcd.vcdresourceset"? The plan is to do this as another task, right?
</blockquote></details>

the "component" in this function refers to CPI, CSI or CAPVCD. I have assumed that AddToVCDResourceSet will be updating `Rde.Status.component.vcdResourceSet` path. The same is for `RemoveFromVCDResourceSet()`. Please let me know if I have to change this design.
___
*[`pkg/vcdsdk/vapp.go` line 516 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N165m4WA33q9TTu3oNB:-N1CLJF_30lUrfL4i0ek:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/41026fed2ade77d4742bc74cd5b26ce811fef30d/pkg/vcdsdk/vapp.go#L516)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please ensure storage profile code (added by Adnan) is retained here. It is relevant in both CPI main and vkp branches. Please track it as separate task if you want to do it as part of another PR
</blockquote></details>

Done.

**Review by arunmk — APPROVED** [review]
:lgtm: with a couple of small comments

> Reviewed 19 of 28 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-:-N1G3Cgt3Y4a7kfgHW24:b-w1syxs)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`pkg/ccm/cloud.go` line 96 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1FQE1n209HcpOgRnsD:-N1FQE1o4AQyZLuRJzSX:b-i4k3gw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/ccm/cloud.go#L96)):*
> ```Go
> 		if cloudConfig.LB.OneArm != nil {
> 			lb = newLoadBalancer(vcdClient, cloudConfig.LB.CertificateAlias, &vcdsdk.OneArm{
> 				StartIP: cloudConfig.LB.OneArm.StartIP,
> ```

We should handle the case where cloudConfig.LB.OneArm could be nil (because customer did not pass it). I remember seeing a test for this.
___
*[`pkg/cpisdk/common_system_test.go` line 72 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1FtPVSDVysiurMrciT:-N1FtPVSDVysiurMrciU:b7k17w1) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/cpisdk/common_system_test.go#L72)):*
> ```Go
> }
> 
> //func getOneArmValStrict(val interface{}, defaultVal *config.OneArm) *config.OneArm {
> ```

If we don't use it let us just delete it
___
*[`pkg/cpisdk/cpi_gateway_manager_system_test.go` line 71 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1FteoOElzySswJ8EsX:-N1FteoOElzySswJ8EsY:b4a5k8g) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/cpisdk/cpi_gateway_manager_system_test.go#L71)):*
> ```Go
> 		EndIP:   cloudConfig.LB.OneArm.EndIP,
> 	}
> 	freeIP, err = cgm.CreateLoadBalancer(ctx, virtualServiceNamePrefix,
> ```

We had a test earlier with a nil `oneArm` as well. We should keep that test.
___
*[`pkg/vcdsdk/defined_entity_test.go` line 10 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1Fx8m30ACLfH7qn7pw:-N1Fx8m30ACLfH7qn7px:bn6nsut) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/vcdsdk/defined_entity_test.go#L10)):*
> ```Go
> )
> 
> //func TestUpgradeCPISectionInStatus(t *testing.T) {
> ```

Can you add a comment or a TOFO mentioning why this has been commented out

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69)* status: 18 of 31 files reviewed, 9 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`pkg/ccm/cloud.go` line 96 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1FQE1n209HcpOgRnsD:-N1Kx6F9ASVzwOHe4ftJ:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/ccm/cloud.go#L96)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We should handle the case where cloudConfig.LB.OneArm could be nil (because customer did not pass it). I remember seeing a test for this.
</blockquote></details>

Done.
___
*[`pkg/cpisdk/common_system_test.go` line 72 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1FtPVSDVysiurMrciT:-N1KyAVy1cK47JZgyWUk:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/cpisdk/common_system_test.go#L72)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

If we don't use it let us just delete it
</blockquote></details>

Done.
___
*[`pkg/cpisdk/cpi_gateway_manager_system_test.go` line 71 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1FteoOElzySswJ8EsX:-N1Kygn292q5jqwf2ql3:bluildy) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/cpisdk/cpi_gateway_manager_system_test.go#L71)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We had a test earlier with a nil `oneArm` as well. We should keep that test.
</blockquote></details>

do you mean https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd398979b58ae8e268094dc0b9cac2738b47daff/pkg/vcdclient/auth_system_test.go#L76-L83?
___
*[`pkg/vcdsdk/defined_entity_test.go` line 10 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1Fx8m30ACLfH7qn7pw:-N1KyvYV56yO60gi1vB4:b77sacf) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/vcdsdk/defined_entity_test.go#L10)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can you add a comment or a TOFO mentioning why this has been commented out
</blockquote></details>

I have added this test to cpisdk as this function was specific to CPI

**Comment by Anirudh9794** [comment]
*[`pkg/cpisdk/cpi_gateway_manager_system_test.go` line 71 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/69#-N1FteoOElzySswJ8EsX:-N1M5ufmElPkpKvKEfcL:b-fl7oj1) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/fd55b1a2a6c19ba0d131556f17067d1923c4f3ad/pkg/cpisdk/cpi_gateway_manager_system_test.go#L71)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

do you mean https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd398979b58ae8e268094dc0b9cac2738b47daff/pkg/vcdclient/auth_system_test.go#L76-L83?
</blockquote></details>

I ran the tests with oneArm set to nil. There were some issues with UpdateLoadBalancer. After discussion, I have added a TODO for UpdateLB() to check for oneArm == nil condition when we get to implementation of LoadBalancer without oneArm property

**Pull request merged**
