### PR TITLE
[VCDA-3670] Add back VApp name as function param in VDCManager (#74)

### PR DESCRIPTION
**Pull request by Anirudh9794**
* add back VApp name as function param in VDCManager

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/75)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/75#-:-N1er3yj6Y5UkOonaPvC:bnfp4nl)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

___
*[`pkg/vcdsdk/vapp_test.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/75#-N1es-256aYWK_49Xz80:-N1es-256aYWK_49Xz81:b-ob9ng2) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a6a78ba56ea2c3f27719da755e489aab1d91f526/pkg/vcdsdk/vapp_test.go#L53)):*
> ```Go
> 	vms, err := vdcManager.FindAllVMsInVapp(vAppName)
> 	assert.NoError(t, err, "unable to find VMs in vApp")
> 	assert.NotNil(t, vms, "some VMs should be returned")
> ```

Just curious if this test case would fail since we are creating a new vApp and not adding any VMs to it, would this return {vms: nil, err: nil}?



_Code quote:_
```Go
	vms, err := vdcManager.FindAllVMsInVapp(vAppName)
	assert.NoError(t, err, "unable to find VMs in vApp")
	assert.NotNil(t, vms, "some VMs should be returned")
```

**Comment by Anirudh9794** [comment]
*[`pkg/vcdsdk/vapp_test.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/75#-N1es-256aYWK_49Xz80:-N1etNKC4h0GeFT8RFpj:b-fiuxa4) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a6a78ba56ea2c3f27719da755e489aab1d91f526/pkg/vcdsdk/vapp_test.go#L53)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Just curious if this test case would fail since we are creating a new vApp and not adding any VMs to it, would this return {vms: nil, err: nil}?
</blockquote></details>

Yes, this test was copied from CAPVCD. Since this is a task for refactor, I didn't correct this test case. Will Add a TODO here though. Most of the tests which were in CAPVCD made a lot of assumptions. Like ComputePolicy test assumes that there is a compute policy by name 2core2gb, Vapp tests assume that there is a template with a specific name already present before running the test.

I will also create a jira task to record the tests. Thanks for bringing this up.

**Comment by Anirudh9794** [comment]
*[`pkg/vcdsdk/vapp_test.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/75#-N1es-256aYWK_49Xz80:-N1ewwQ17uZYszIVxbrB:bwip2pw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a6a78ba56ea2c3f27719da755e489aab1d91f526/pkg/vcdsdk/vapp_test.go#L53)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Yes, this test was copied from CAPVCD. Since this is a task for refactor, I didn't correct this test case. Will Add a TODO here though. Most of the tests which were in CAPVCD made a lot of assumptions. Like ComputePolicy test assumes that there is a compute policy by name 2core2gb, Vapp tests assume that there is a template with a specific name already present before running the test.

I will also create a jira task to record the tests. Thanks for bringing this up.
</blockquote></details>

Created task https://jira.eng.vmware.com/browse/VCDA-3675

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/75#-:-N1f6VNqDIuTDX8SzIFM:bg7igkv)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @lzichong and @rocknes)

**Pull request merged**
