### PR TITLE
[VCDA-4627] Cloud api calls should send in a tenant context header to scope requests to the cluster's organization

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Cloud api requests should be scoped to the cluster's organization.
* fixes bugs where a system administrator user sees inconsistent behavior where VCD resources outside the cluster organization is being accessed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
There is one important question that I want clarified and then I'll give a +1

Another separate question which maybe needs a ticket on CSE 4.0 (maybe post-GA as well): can we capture the Org ID in some struct itself along with the OrgName, so that we don't keep getting it repeatedly? Aniruddha, can you create a ticket on it and we can discuss there.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139#-:-NE6qzPN4vG7th0yJJy9:bwrrx8n)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[`pkg/vcdclient/gateway.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139#-NE6pJfS8m7ZrJQuyK62:-NE6pJfS8m7ZrJQuyK63:bs9uvud) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4956c427e4701cb820c4dc4a3ba0be2a3cc013f9/pkg/vcdclient/gateway.go#L53)):*
> ```Go
> 
> 		for _, ovdcNetwork := range ovdcNetworks.Values {
> 			if networkFound {
> ```

I think this should be 
```
if ovdcNetwork.Name == client.NetworkName {
    if networkFound {
        // report error
    }

    ovdcNetworkID = ovdcNetwork.Id
    networkFound = true
}
```

Can you tell me if I am misunderstanding this?
___
*[`pkg/vcdswaggerclient/api_certificate_library_modified.go` line 29 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139#-NE6l80m7_bLKGmdm7Ks:-NE6l80m7_bLKGmdm7Kt:b-ullhu6) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4956c427e4701cb820c4dc4a3ba0be2a3cc013f9/pkg/vcdswaggerclient/api_certificate_library_modified.go#L29)):*
> ```Go
> 
> const (
> 	TenantContextHeader = "X-VMWARE-VCLOUD-TENANT-CONTEXT"
> ```

This is fine here, but for the CSE 4.0 effort, it will be better to create a new file named `vcdconstants.go` and put this constant there.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk)

___
*[`pkg/vcdclient/gateway.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139#-NE6pJfS8m7ZrJQuyK62:-NE6tkuCAlWsia3Dr-Sq:b-nefnic) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4956c427e4701cb820c4dc4a3ba0be2a3cc013f9/pkg/vcdclient/gateway.go#L53)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think this should be 
```
if ovdcNetwork.Name == client.NetworkName {
    if networkFound {
        // report error
    }

    ovdcNetworkID = ovdcNetwork.Id
    networkFound = true
}
```

Can you tell me if I am misunderstanding this?
</blockquote></details>

sorry its a mistake from me. There is a mistake in the changes for 4.0 stack. Will track it and get it fixed.

**Comment by Anirudh9794** [comment]
*[`pkg/vcdswaggerclient/api_certificate_library_modified.go` line 29 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139#-NE6l80m7_bLKGmdm7Ks:-NE71hth1ALVG1GsD4XE:b-9xducw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4956c427e4701cb820c4dc4a3ba0be2a3cc013f9/pkg/vcdswaggerclient/api_certificate_library_modified.go#L29)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This is fine here, but for the CSE 4.0 effort, it will be better to create a new file named `vcdconstants.go` and put this constant there.
</blockquote></details>

Will include this change in the changes to CSE 4.0.

**Comment by Anirudh9794** [comment]
*[`pkg/vcdclient/gateway.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139#-NE6pJfS8m7ZrJQuyK62:-NE71cHyCQIoI3iY1wrJ:bmqwhrz) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4956c427e4701cb820c4dc4a3ba0be2a3cc013f9/pkg/vcdclient/gateway.go#L53)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

sorry its a mistake from me. There is a mistake in the changes for 4.0 stack. Will track it and get it fixed.
</blockquote></details>

Addressed this for the current PR

**Comment by Anirudh9794** [comment]
I have created to reduce the GetOrgByName() calls. (VCDA-4643)

**Review by arunmk — APPROVED** [review]
:lgtm_strong: thanks!

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139#-:-NE8UetC8uUFehF5wImc:b-c5hpsr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
