### PR TITLE
[VKCI-104] Fix for nil pointer exception when subnet is null from usage of IP Spaces

### PR DESCRIPTION
**Pull request by lzichong**
Tested against VCD 10.4.1 GA using IP Spaces. Verified that CCM pod is no longer crashing when IP's can't be fetched:

E1222 01:39:59.854969       1 controller.go:307] error processing service default/ingress-nginx-controller (will retry): failed to ensure load balancer: unable to create loadbalancer for ports [[]vcdsdk.PortDetails{vcdsdk.PortDetails{Protocol:"HTTP", PortSuffix:"http", ExternalPort:80, InternalPort:30096, UseSSL:false, CertAlias:""}, vcdsdk.PortDetails{Protocol:"HTTPS", PortSuffix:"https", ExternalPort:443, InternalPort:32018, UseSSL:false, CertAlias:""}}]: [unable to get unused IP address from subnet []: [unable to get any ipRanges in gateway]]

Previously, the CCM pod would crash due to using Subnet.Values when it is null.

Signed-off-by: lzichong <lzichong@vmware.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/198)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
*[`pkg/vcdsdk/ipam.go` line 62 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/198#-NJrYoAC1zZgsb4GhjCM:-NJrYoAC1zZgsb4GhjCN:be00yg) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4e4ac36cc5a6d374819dee8111c4561184dc52ac/pkg/vcdsdk/ipam.go#L62)):*
> ```Go
> 		// A nil check is needed for edgeGWUplink.Subnet because there is a possibility for subnet to be null which can cause CCM pod to crash.
> 		// An example is the usage of IP Spaces which is in VCD 10.4.1.
> 		if edgeGWUplink.Subnets != nil {
> ```

shouldn't this check be `edgeGWUplink.Subnets == nil` ?

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/198)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arunmk and @lzichong)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/198)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/vcdsdk/ipam.go` line 62 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/198#-NJrYoAC1zZgsb4GhjCM:-NJrZQogAVqrP8cA-J9a:b-38sh8f) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4e4ac36cc5a6d374819dee8111c4561184dc52ac/pkg/vcdsdk/ipam.go#L62)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

shouldn't this check be `edgeGWUplink.Subnets == nil` ?
</blockquote></details>

Updated, yes it should be  == nil sorry about that, thanks for the catch!

**Review by arunmk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/198#-:-NJsRUXsBzJc_c-mKfsX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/198)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong)

**Pull request merged**
