### PR TITLE
update NewClientWithSecrets() with minimal parameters to create a client

### PR DESCRIPTION
**Pull request by Anirudh9794**
ticket: VCDA-3437

* create managers for each of the vcdclient functions
* Moved some parameters out of config.VCD to config.LB in cloud config.
* Updated tests

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 93 of 93 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @lzichong)

___
*[pkg/ccm/cloud.go, line 13 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CR-DC-Adm2c1tWda_:-N0CR-DC-Adm2c1tWdaa:b-if5b5h) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8257fc81a368a01fe53f9b0bcfde4fb2daba6a24/pkg/ccm/cloud.go#L13)):*
> ```Go
> 	"fmt"
> 	"github.com/vmware/cloud-provider-for-cloud-director/pkg/config"
> 	"github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdclient"
> ```

Aniruddh, do you see any issues renaming the pkg 'vcdclient' to 'vcdsdk'?
Currently, the pkg holds several other files (vapp.go etc) in addition to client generation file auth.go. Please check if we can safely rename it to vcdsdk.



_Code quote:_
```Go
vcdclient
```
___
*[pkg/vcdclient/rde.go, line 17 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CShoGA9SnavhGb_yz:-N0CShoGA9SnavhGb_z-:bc55x11) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8257fc81a368a01fe53f9b0bcfde4fb2daba6a24/pkg/vcdclient/rde.go#L17)):*
> ```Go
> )
> 
> type RDEManager struct {
> ```

I assume crud  methods of vcdresourceset will land here
___
*[pkg/vcdclient/vms.go, line 22 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CT2KG8302gR9bJdcJ:-N0CT2KG8302gR9bJdcK:b-5xx5ho) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8257fc81a368a01fe53f9b0bcfde4fb2daba6a24/pkg/vcdclient/vms.go#L22)):*
> ```Go
> )
> 
> type VMManager struct {
> ```

In capvcd, I added a manager called vdcmanager which would call both vapp and VM methods. I am not asking you to follow that pattern, but just ensure your new managers cover all the methods and files cleanly. And capvcd needs to be refactored accordingly.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64)* status: 91 of 95 files reviewed, 3 unresolved discussions (waiting on @arunmk, @lzichong, and @sahithi)

___
*[pkg/ccm/cloud.go, line 13 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CR-DC-Adm2c1tWda_:-N0Cd-QZDD0ZBMh2OFRB:b5dsxdw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8257fc81a368a01fe53f9b0bcfde4fb2daba6a24/pkg/ccm/cloud.go#L13)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Aniruddh, do you see any issues renaming the pkg 'vcdclient' to 'vcdsdk'?
Currently, the pkg holds several other files (vapp.go etc) in addition to client generation file auth.go. Please check if we can safely rename it to vcdsdk.
</blockquote></details>

Yes. I think it should be ok to rename the package to `vcdsdk`
___
*[pkg/vcdclient/rde.go, line 17 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CShoGA9SnavhGb_yz:-N0Cd7tk4laS9qQRAsND:b2nhswy) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8257fc81a368a01fe53f9b0bcfde4fb2daba6a24/pkg/vcdclient/rde.go#L17)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I assume crud  methods of vcdresourceset will land here
</blockquote></details>

Yes
___
*[pkg/vcdclient/vms.go, line 22 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CT2KG8302gR9bJdcJ:-N0CdOOi0PhD0cEIYS-1:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8257fc81a368a01fe53f9b0bcfde4fb2daba6a24/pkg/vcdclient/vms.go#L22)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

In capvcd, I added a manager called vdcmanager which would call both vapp and VM methods. I am not asking you to follow that pattern, but just ensure your new managers cover all the methods and files cleanly. And capvcd needs to be refactored accordingly.
</blockquote></details>

Done.

**Review by lzichong — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[pkg/vcdclient/gateway_system_test.go, line 336 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CivGZ4qWXzZtXWQB3:-N0CivGZ4qWXzZtXWQB4:b-r4pemy) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd92d9dae29202c1e9c8c99cd7b6abfd9aa9c95c/pkg/vcdclient/gateway_system_test.go#L336)):*
> ```Go
> 	var vsRef *swagger.EntityReference
> 	for i := 0; i < BusyRetries; i ++ {
> 		vsRef, err = gm.createVirtualService(ctx, virtualServiceName, lbPoolRef, segRef,
> ```

Is this to ensure that if there's any network connectivity slowness that it will at least try a few times before failing the test?



_Code quote:_
```Go
	var vsRef *swagger.EntityReference
	for i := 0; i < BusyRetries; i ++ {
		vsRef, err = gm.createVirtualService(ctx, virtualServiceName, lbPoolRef, segRef,
			internalIP, externalIP, "HTTP", 80, false, "", cloudConfig.ClusterID)
		if err != nil {
			if _, ok := err.(*VirtualServicePendingError); !ok {
				break
			}
		}
	}
```
___
*[pkg/vcdclient/gateway_system_test.go, line 450 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CkTjl3AhsSBEvZDyN:-N0CkTjl3AhsSBEvZDyO:b-z2bn39) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd92d9dae29202c1e9c8c99cd7b6abfd9aa9c95c/pkg/vcdclient/gateway_system_test.go#L450)):*
> ```Go
> 		certName = fmt.Sprintf("%s-cert", cloudConfig.ClusterID)
> 	}
> 	vsRef, err := gm.createVirtualService(ctx, virtualServiceName, lbPoolRef, segRef,
> ```

Similar comment to the HTTP test, was just wondering why was the loop implemented in HTTP but not in HTTPS?



_Code quote:_
```Go
	vsRef, err := gm.createVirtualService(ctx, virtualServiceName, lbPoolRef, segRef,
		internalIP, externalIP, "HTTPS", 443, true, certName, cloudConfig.ClusterID)
```

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[pkg/ccm/cloud.go, line 84 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CmsO747BNaZ3s-6UC:-N0CmsO8EdnsKr66Iwdj:b-qy2689) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd92d9dae29202c1e9c8c99cd7b6abfd9aa9c95c/pkg/ccm/cloud.go#L84)):*
> ```Go
> 	// setup LB only if the gateway is not NSX-T
> 	var lb cloudProvider.LoadBalancer = nil
> 	gm, err := vcdclient.NewGatewayManager(context.Background(), vcdClient, cloudConfig.LB.VDCNetwork, cloudConfig.LB.VIPSubnet)
> ```

Sorry I missed this earlier, but should there be an error check here?



_Code quote:_
```Go
	gm, err := vcdclient.NewGatewayManager(context.Background(), vcdClient, cloudConfig.LB.VDCNetwork, cloudConfig.LB.VIPSubnet)
	if !gm.IsNSXTBackedGateway() {
		klog.Infof("Gateway of network [%s] not backed by NSX-T. Hence LB will not be initialized.",
			cloudConfig.LB.VDCNetwork)
	} else {
		lb = newLoadBalancer(vcdClient, cloudConfig.LB.CertificateAlias, cloudConfig.LB.OneArm,
			cloudConfig.LB.VDCNetwork, cloudConfig.LB.VIPSubnet, cloudConfig.ClusterID)
	}
```

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64)* status: 82 of 98 files reviewed, 6 unresolved discussions (waiting on @arunmk, @lzichong, and @sahithi)

___
*[pkg/ccm/cloud.go, line 84 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CmsO747BNaZ3s-6UC:-N0CzSdp2CB7LV7TkQ31:b2jjg11) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd92d9dae29202c1e9c8c99cd7b6abfd9aa9c95c/pkg/ccm/cloud.go#L84)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Sorry I missed this earlier, but should there be an error check here?
</blockquote></details>

Yes, thanks! Missed this
___
*[pkg/vcdclient/gateway_system_test.go, line 336 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CivGZ4qWXzZtXWQB3:-N0CnQUS0O8pLBa2UXcz:b-aam4jr) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd92d9dae29202c1e9c8c99cd7b6abfd9aa9c95c/pkg/vcdclient/gateway_system_test.go#L336)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Is this to ensure that if there's any network connectivity slowness that it will at least try a few times before failing the test?
</blockquote></details>

I added this retry logic to make sure tests don't fail because virtual service is in a pending state.
___
*[pkg/vcdclient/gateway_system_test.go, line 450 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0CkTjl3AhsSBEvZDyN:-N0CzkxYER4Bsd8-2QXo:b-7wm8an) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dd92d9dae29202c1e9c8c99cd7b6abfd9aa9c95c/pkg/vcdclient/gateway_system_test.go#L450)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Similar comment to the HTTP test, was just wondering why was the loop implemented in HTTP but not in HTTPS?
</blockquote></details>

Yeah, i missed adding here. I added it just now

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-:-N0D2N6f2vm1EUqC3Pam:bg7igkv)* status: 82 of 98 files reviewed, 6 unresolved discussions (waiting on @arunmk, @lzichong, and @sahithi)

**Review by lzichong — APPROVED** [review]
:lgtm: after the addressing the err check

> Reviewed 12 of 16 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-:-N0D5QVD3zg2H9Npxptl:b7d2jla)* status: 95 of 98 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @arunmk, @lzichong, and @sahithi)

___
*[pkg/ccm/loadbalancer.go, line 168 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0D24V77eRFEuU79Fld:-N0D24V77eRFEuU79Fle:b-csxd7e) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4059ffbff0e95596fd150ea78455f4b840ea9d7b/pkg/ccm/loadbalancer.go#L168)):*
> ```Go
> 	virtualServiceNamePrefix := lb.getLoadBalancerPrefix(ctx, service)
> 	virtualIP := ""
> 	gm, err := vcdsdk.NewGatewayManager(ctx, lb.vcdClient, lb.ovdcNetworkName, lb.ipamSubnet)
> ```

Should there be an err check here as well?



_Code quote:_
```Go
	gm, err := vcdsdk.NewGatewayManager(ctx, lb.vcdClient, lb.ovdcNetworkName, lb.ipamSubnet)
	for _, port := range service.Spec.Ports {
```
___
*[pkg/vcdsdk/gateway_system_test.go, line 461 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0D4bUlD4hayfWEuYTL:-N0D4bUmAgVhWkYIZk2C:bh0n5wn) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4059ffbff0e95596fd150ea78455f4b840ea9d7b/pkg/vcdsdk/gateway_system_test.go#L461)):*
> ```Go
> 	for i := 0; i < BusyRetries; i ++ {
> 		vsRef, err = gm.createVirtualService(ctx, virtualServiceName, lbPoolRef, segRef,
> 			internalIP, externalIP, "HTTP", 80, false, "", cloudConfig.ClusterID)
> ```

Should HTTP be HTTPS and Port here be 443 for HTTPS? 



_Code quote:_
```Go
	for i := 0; i < BusyRetries; i ++ {
		vsRef, err = gm.createVirtualService(ctx, virtualServiceName, lbPoolRef, segRef,
			internalIP, externalIP, "HTTP", 80, false, "", cloudConfig.ClusterID)
```

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64)* status: 94 of 98 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @arunmk, @lzichong, and @sahithi)

___
*[pkg/ccm/loadbalancer.go, line 168 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/64#-N0D24V77eRFEuU79Fld:-N0DByOP2PRK2oAPuNxf:bily6mc) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/4059ffbff0e95596fd150ea78455f4b840ea9d7b/pkg/ccm/loadbalancer.go#L168)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Should there be an err check here as well?
</blockquote></details>

Yes. Thanks!

**Pull request merged**
