### PR TITLE
[VCDA-3422] CPI support for multiple virtual services with the same ip and different ports

### PR DESCRIPTION
**Pull request by ltimothy7**
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
Testing has been done to test this feature on VCD 10.4 (oneArm and no oneArm) and on VCD 10.3.3 for normal behavior

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-:-N3aLkh17kUr6vzaFJuf:b-9uweac)* status: 0 of 6 files reviewed, all discussions resolved

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[`manifests/vcloud-configmap.yaml` line 22 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3ba62ZDnhMZCgHL0nl:-N3ba62ZDnhMZCgHL0nm:b-5ilk7t) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/manifests/vcloud-configmap.yaml#L22)):*
> ```YAML
>       vipSubnet: VIP_SUBNET_CIDR
>       certAlias: CLUSTER_ID-cert
>       useVsSharedIP: true # supported for VCD >= 10.4
> ```

we should keep this as false since we use this manifest directly in CPI installation scripts
___
*[`pkg/ccm/loadbalancer.go` line 185 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3baq7D4frEH7V7i0Ze:-N3baq7D4frEH7V7i0Zf:b5uzlau) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/ccm/loadbalancer.go#L185)):*
> ```Go
> 					virtualServiceName, err)
> 		}
> 		portNameToIP[port.Name] = virtualIP
> ```

Maybe this should be within the `if virtualIP != ""` block? Especially since we are doing the `len(portNameToIP)` check later.

EDIT: I think this can remain unchanged since the `""` value is used later. We should just change the len check below.
___
*[`pkg/ccm/loadbalancer.go` line 189 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bbHMiEh7uJ26Vn9QN:-N3bbHMiEh7uJ26Vn9QO:b-4rlmay) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/ccm/loadbalancer.go#L189)):*
> ```Go
> 			if ingressVirtualIP != "" && ingressVirtualIP != virtualIP {
> 				return nil, nil,
> 				fmt.Errorf("more than one virtual ip found: [%s] and [%s]", virtualIP, ingressVirtualIP)
> ```

nit: extra indent
___
*[`pkg/ccm/loadbalancer.go` line 340 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bcAel3wpwK8LninnM:-N3bcAel3wpwK8LninnN:b-a456hw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/ccm/loadbalancer.go#L340)):*
> ```Go
> 
> 	// golang doesn't have the set data structure
> 	portNamesToCreate := make(map[string]bool)
> ```

We are basically getting a bool out of this, correct? In that case, can we do like this?
```
lbExists := true
for _, ip := range portNameToIPMap {
    if ip == "" {
        lbExists = false
        break
    }
}
```
___
*[`pkg/config/cloudconfig.go` line 56 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bcZuG5MmYOFp4b1zf:-N3bcZuHEouJqV8POH4t:b-9iarr7) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/config/cloudconfig.go#L56)):*
> ```Go
> 	CertificateAlias string  `yaml:"certAlias"`
> 	VDCNetwork       string  `yaml:"network"`
> 	VIPSubnet     string `yaml:"vipSubnet"`
> ```

`go fmt` to set the indentation cleanly
___
*[`pkg/vcdsdk/gateway.go` line 1365 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3beezz88meKM4t1Ffs:-N3beezz88meKM4t1Fft:b-xhxtgj) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/vcdsdk/gateway.go#L1365)):*
> ```Go
> 	// 3 variables: useVsSharedIP, oneArm, sharedIP
> 	// if useVsSharedIP is true and oneArm is nil, no internal ip is used
> 	// if useVsSharedIP is true and oneArm is not nil, an internal ip will be used and shared
> ```

Can you also add the other cases:
```
// if useVsSharedIP is false and oneArm is nil: this is an error case which is handled earlier
// if useVsSharedIP is false and oneArm is not nil, a pair of internal IPs will be used and not shared
```
___
*[`pkg/vcdsdk/gateway.go` line 1366 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bgsXhBRPWYpX8rIZ_:-N3bgsXhBRPWYpX8rIZa:b-vzqtjy) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/vcdsdk/gateway.go#L1366)):*
> ```Go
> 	// if useVsSharedIP is true and oneArm is nil, no internal ip is used
> 	// if useVsSharedIP is true and oneArm is not nil, an internal ip will be used and shared
> 	if useVsSharedIP && oneArm == nil {  // no internal ip used
> ```

Can we mention `so no dnat rule needed`
___
*[`pkg/vcdsdk/gateway.go` line 1379 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bfLBiEggqvjF85kQg:-N3bfLBiEggqvjF85kQh:b-yyutjx) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/vcdsdk/gateway.go#L1379)):*
> ```Go
> 	}
> 
> 	if externalIP == "" {
> ```

Can we move this block to above the 2 cases you are handling above to make things cleaner.

EDIT: I think this block is the core and can be simplified a bit like this with extra redundancy but more clarity. We can chat in the morning

```
        type dnatRuleStruct struct {
            externalIP string
            externalPort int
            internalIP string
            internalPort int
        }
        dnatRulesToCreate := make([]dnatRuleStruct, 0)
	if useVsSharedIP && oneArm == nil {  // no internal ip used, so no dnat Rule needed
		if sharedVirtualIP != "" { // shared virtual ip is an external ip
			externalIP = sharedVirtualIP
		}
	} else if useVsSharedIP && oneArm != nil { // internal ip used, dnat rules needed
		if sharedInternalIP == "" { // no dnat rule has been created yet
			sharedInternalIP, err = gm.GetUnusedInternalIPAddress(ctx, oneArm)
			if err != nil {
				return "", fmt.Errorf("unable to get internal IP address for one-arm mode: [%v]", err)
			}
                        for _, portDetails := range portDetailsList {
                            dnatRulesToCreate = append(dnatRulesToCreate, dnatRuleStruct{
                                externalIP: sharedVirtualIP
                                // and other entries
                                })
                        }
		} 
	} else { // external and internal ip present, dnat rules needed
        }
```

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[`manifests/vcloud-configmap.yaml` line 22 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3ba62ZDnhMZCgHL0nl:-N3bjjUJ7_AyoUNyNCOa:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/manifests/vcloud-configmap.yaml#L22)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

we should keep this as false since we use this manifest directly in CPI installation scripts
</blockquote></details>

Done.
___
*[`pkg/ccm/loadbalancer.go` line 185 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3baq7D4frEH7V7i0Ze:-N3bl8qv7DZ1klqAo7Uk:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/ccm/loadbalancer.go#L185)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Maybe this should be within the `if virtualIP != ""` block? Especially since we are doing the `len(portNameToIP)` check later.

EDIT: I think this can remain unchanged since the `""` value is used later. We should just change the len check below.
</blockquote></details>

Done.
___
*[`pkg/ccm/loadbalancer.go` line 340 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bcAel3wpwK8LninnM:-N3blY6K4SFxFf0p6B14:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/ccm/loadbalancer.go#L340)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We are basically getting a bool out of this, correct? In that case, can we do like this?
```
lbExists := true
for _, ip := range portNameToIPMap {
    if ip == "" {
        lbExists = false
        break
    }
}
```
</blockquote></details>

Done.
___
*[`pkg/config/cloudconfig.go` line 56 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bcZuG5MmYOFp4b1zf:-N3blrxA9Qledf6ORmSN:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/config/cloudconfig.go#L56)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

`go fmt` to set the indentation cleanly
</blockquote></details>

Done.
___
*[`pkg/vcdsdk/gateway.go` line 1365 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3beezz88meKM4t1Ffs:-N3blvSv8X92AjKxg_2w:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/vcdsdk/gateway.go#L1365)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can you also add the other cases:
```
// if useVsSharedIP is false and oneArm is nil: this is an error case which is handled earlier
// if useVsSharedIP is false and oneArm is not nil, a pair of internal IPs will be used and not shared
```
</blockquote></details>

Done.
___
*[`pkg/vcdsdk/gateway.go` line 1366 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3bgsXhBRPWYpX8rIZ_:-N3bmfiy31YzIfvuFYJH:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/899d4f2bfc3e938a67e0cf8111172deb642de7ab/pkg/vcdsdk/gateway.go#L1366)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we mention `so no dnat rule needed`
</blockquote></details>

Done.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-:-N3eUOnH6dxMchsjZdHq:b593w57)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @arunmk and @ltimothy7)

**Review by arunmk — APPROVED** [review]
> Reviewed 9 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89)* status: 9 of 17 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @ltimothy7)

___
*[`pkg/ccm/loadbalancer.go` line 344 at r4](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89#-N3geZmL0Q7nshAp4n6i:-N3geZmL0Q7nshAp4n6j:b-gcrp6f) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/da661866d513b4a0779f74c5fc838a7de2711336/pkg/ccm/loadbalancer.go#L344)):*
> ```Go
> 	for _, ip := range portNameToIPMap {
> 		if ip == "" {
> 			lbExists = false
> ```

we can break immediately, correct?

**Pull request merged**
