### PR TITLE
[VCDA-4195] fixed function calls in gateway_system_test.go

### PR DESCRIPTION
**Pull request by rliang88**
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @rliang88 and @sahithi)

___
*[`pkg/vcdsdk/gateway_system_test.go` line 580 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-ND4juG53Dxiz-MF_GbN:-ND4juG53Dxiz-MF_GbO:b-7k4tcq) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/437f0192be2406b726eb4948fbc58fb6ef551b91/pkg/vcdsdk/gateway_system_test.go#L580)):*
> ```Go
> 	assert.NoError(t, err, "HTTP Load Balancer should be updated")
> 
> 	_, err = gm.UpdateLoadBalancer(ctx, lbPoolNamePrefix+"-https", virtualServiceNamePrefix+"-https", updatedIps, updatedInternalPort, 443, nil, false, "HTTP", &util.AllocatedResourcesMap{})
> ```

Protocol should be "HTTPS"
___
*[`pkg/vcdsdk/gateway_system_test.go` line 590 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-ND4inmnD0qh12FsRVRR:-ND4inmnD0qh12FsRVRS:b8uurt2) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/437f0192be2406b726eb4948fbc58fb6ef551b91/pkg/vcdsdk/gateway_system_test.go#L590)):*
> ```Go
> 	assert.NoError(t, err, "HTTP Load Balancer should be updated")
> 
> 	_, err = gm.UpdateLoadBalancer(ctx, lbPoolNamePrefix+"-https", virtualServiceNamePrefix+"-https", updatedIps, updatedInternalPort, updatedExternalPortHttps, nil, false, "HTTP", &util.AllocatedResourcesMap{})
> ```

protocol should be "HTTPS"
___
*[`pkg/vcdsdk/gateway_system_test.go` line 597 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-ND4iruw7b8_KxOzxKST:-ND4iruw7b8_KxOzxKSU:b8uurt2) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/437f0192be2406b726eb4948fbc58fb6ef551b91/pkg/vcdsdk/gateway_system_test.go#L597)):*
> ```Go
> 	assert.NoError(t, err, "HTTP Load Balancer should be updated")
> 
> 	_, err = gm.UpdateLoadBalancer(ctx, lbPoolNamePrefix+"-https", virtualServiceNamePrefix+"-https", updatedIps, updatedInternalPort, updatedExternalPortHttps, nil, false, "HTTP", &util.AllocatedResourcesMap{})
> ```

protocol should be "HTTPS"
___
*[`pkg/vcdsdk/gateway_system_test.go` line 603 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-ND4j-pv1NE2xOiS7Osl:-ND4j-pv1NE2xOiS7Osm:bua4ts5) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/437f0192be2406b726eb4948fbc58fb6ef551b91/pkg/vcdsdk/gateway_system_test.go#L603)):*
> ```Go
> 	assert.NoError(t, err, "Load Balancer should be deleted")
> 
> 	freeIPObtained, _, err = gm.GetLoadBalancer(ctx, virtualServiceNameHttp, "", oneArm)
> ```

The actual name of the load balancer pool should be provided instead of "". The test over here is to check if the loadbalancer is really deleted by the previous DeleteLoadBalancer call,
___
*[`pkg/vcdsdk/gateway_system_test.go` line 607 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-ND4jiXRCAvbYz0GdkcG:-ND4jiXRCAvbYz0GdkcH:b4qw5ek) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/437f0192be2406b726eb4948fbc58fb6ef551b91/pkg/vcdsdk/gateway_system_test.go#L607)):*
> ```Go
> 	assert.Empty(t, freeIPObtained, "The VIP should not be found")
> 
> 	freeIPObtained, _, err = gm.GetLoadBalancer(ctx, virtualServiceNameHttps, "", oneArm)
> ```

The same comment to use the actual name of the loadbalancer pool instead of ""
___
*[`pkg/vcdsdk/gateway_system_test.go` line 616 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-ND4jocn0ruQjXJWql4B:-ND4jocn0ruQjXJWql4C:b-7k4tcq) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/437f0192be2406b726eb4948fbc58fb6ef551b91/pkg/vcdsdk/gateway_system_test.go#L616)):*
> ```Go
> 	_, err = gm.UpdateLoadBalancer(ctx, lbPoolNamePrefix+"-http", virtualServiceNamePrefix+"-http", updatedIps, updatedInternalPort, 80, nil, false, "HTTP", &util.AllocatedResourcesMap{})
> 	assert.Error(t, err, "updating deleted HTTP Load Balancer should be an error")
> 	_, err = gm.UpdateLoadBalancer(ctx, lbPoolNamePrefix+"-https", virtualServiceNamePrefix+"https", updatedIps, updatedInternalPort, 43, nil, false, "HTTP", &util.AllocatedResourcesMap{})
> ```

Protocol should be "HTTPS"

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @rliang88, and @ymo24)

___
*[`testdata/auth_test.yaml` line 1 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-NDUe_W7DFNCxmctnF7g:-NDUe_W7DFNCxmctnF7h:b6im0dc) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/ccc3d86c625dd417a2c886007f6471d55581a0ef/testdata/auth_test.yaml#L1)):*
> ```YAML
> username: "user"
> ```

Please revert the auth_test.yaml. We usually do not push files under testate folder.

**Review by ymo24 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-:-NDUgj9r8_aAPx8o2hH9:bg7igkv)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @rliang88 and @ymo24)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/130#-:-ND_O4mu5Y-5p5w_cQ3u:bg7igkv)* status: all files reviewed, 7 unresolved discussions (waiting on @rliang88)

**Pull request merged**
