### PR TITLE
[VKCI-159][VKCI-161] add common functions to common testing core

### PR DESCRIPTION
**Pull request by rliang88**
### Functions Implemented: 
- query vApp templates from all catalogs
- get all nodes (including control plane)
- get current cluster's k8s version

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @lzichong, @rliang88, and @ymo24)

___
*[`pkg/testingsdk/vcd_utils.go` line 62 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243#-NRsvtOi9Ofmqd6XC0d0:-NRsvtOi9Ofmqd6XC0d1:b6813v3) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/933e394329ccc44e5ed2166884fb231475e3670d/pkg/testingsdk/vcd_utils.go#L62)):*
> ```Go
> 
> 		for _, vappTemplate := range vappTemplates {
> 			allVappTemplates = append(allVappTemplates, vappTemplate)
> ```

It seems like it's possible for there to be duplicate templates. Could we add a comment about this?

**Review by rliang88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ltimothy7, @lzichong, and @ymo24)

___
*[`pkg/testingsdk/vcd_utils.go` line 62 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243#-NRsvtOi9Ofmqd6XC0d0:-NRt4u2892Bk9CuLKXj_:b8aqn2g) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/933e394329ccc44e5ed2166884fb231475e3670d/pkg/testingsdk/vcd_utils.go#L62)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

It seems like it's possible for there to be duplicate templates. Could we add a comment about this?
</blockquote></details>

Nice catch, I added a comment that the return value may have duplicates.

**Review by ymo24 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ltimothy7, @lzichong, and @rliang88)

___
*[`pkg/testingsdk/vcd_utils.go` line 53 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243#-NRtJPhL7KDE_x8XjUeW:-NRtJPhL7KDE_x8XjUeX:bx9df9e) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1070b1f1d0c4ee8968c31123a7630c48c6a466fc/pkg/testingsdk/vcd_utils.go#L53)):*
> ```Go
> 		catalog, err := clusterOrg.GetCatalogByName(catalogRecord.Name, true)
> 		if err != nil {
> 			return nil, fmt.Errorf("error retreiving catalog %s: [%v]", catalogRecord.Name, err)
> ```

Would you please include org name inside the logging statement?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ltimothy7, @lzichong, and @rliang88)

___
*[`pkg/testingsdk/vcd_utils.go` line 58 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243#-NRtJfe743CiiWPgMRgP:-NRtJfe743CiiWPgMRgQ:b-2guby3) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1070b1f1d0c4ee8968c31123a7630c48c6a466fc/pkg/testingsdk/vcd_utils.go#L58)):*
> ```Go
> 		vappTemplates, err := catalog.QueryVappTemplateList()
> 		if err != nil {
> 			return nil, fmt.Errorf("error retreiving vApp templates from catalog %s: [%v]", catalogRecord.Name, err)
> ```

same here

**Review by ymo24 — COMMENTED** [review]
LGTM after addressing the comments

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243#-:-NRtJl3W2cgOl8G29Kdi:b-wg5q9i)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ltimothy7, @lzichong, and @rliang88)

**Review by lzichong — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rliang88)

**Review by rliang88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ltimothy7, @lzichong, and @ymo24)

___
*[`pkg/testingsdk/vcd_utils.go` line 53 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243#-NRtJPhL7KDE_x8XjUeW:-NRtOtD56IUL85ySVXXX:bb7f2mf) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1070b1f1d0c4ee8968c31123a7630c48c6a466fc/pkg/testingsdk/vcd_utils.go#L53)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Would you please include org name inside the logging statement?
</blockquote></details>

done
___
*[`pkg/testingsdk/vcd_utils.go` line 58 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243#-NRtJfe743CiiWPgMRgP:-NRtOoCB6-Q5uENF09o5:bb7f2mf) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1070b1f1d0c4ee8968c31123a7630c48c6a466fc/pkg/testingsdk/vcd_utils.go#L58)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

same here
</blockquote></details>

done

**Pull request merged**
