### PR TITLE
[VKCI-63], [VKCI-55] CPI Automation - Loadbalancer Tests, Node LCM Tests

### PR DESCRIPTION
**Pull request by lzichong**
Includes E2E CPI Automation from LB Service and Node LCM:

Loadbalancer Tests:
* 1. Creates a Loadbalancer Service
* 2. Verifies External IP and VCD Resources
* 3. Checks network connectivity from external IP
* 4. Ensures Loadbalancer can be deleted / Delete LB Service
* 5. Verifies VCD Resources are no longer present

Node LCM Tests:
* 1. Powers Off 1 Worker VM in VCD (could be any worker)
* 2. Powered off node status should turn to `NotReady`
* 3. Power back on the VM that was powered off in VCD
* 4. Worker Node status should return from `NotReady` -> `Ready`
* 5. Power off and delete the worker node VM in VCD
* 6. Node should be completely removed from list of nodes

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 254 files at r1, 2 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212)* status: 10 of 254 files reviewed, 4 unresolved discussions (waiting on @arunmk, @lzichong, @rliang88, and @ymo24)

___
*[`tests/e2e/loadbalancer_test.go` line 90 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMBefsG8MHZBUfqLW2l:-NMBefsG8MHZBUfqLW2m:b-fb6h5e) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/loadbalancer_test.go#L90)):*
> ```Go
> 	It("should have an external IP and VCD resources", func() {
> 		By("getting the next available unused external IP from our edge gateway")
> 		availableIp, err := gatewayMgr.GetUnusedExternalIPAddress(ctx, ipamSubnet)
> ```

As discussed, can we move this function call to before Case 1 is defined?
___
*[`tests/e2e/loadbalancer_test.go` line 159 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMFR_Ei3UXZ8j0rfSBa:-NMFR_Ei3UXZ8j0rfSBb:b-j8qokw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/loadbalancer_test.go#L159)):*
> ```Go
> 
> 		By("cleaning up the remainder of deployment and namespaces")
> 		err = tc.DeleteDeployment(ctx, ns.Name, testDeploymentName)
> ```

Another question, what if there is an error in the execution? Will other tests continue to execute?
___
*[`tests/e2e/node_test.go` line 58 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMFT1AvBsFDufYc69l3:-NMFT1AvBsFDufYc69l4:b-vvs4ib) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/node_test.go#L58)):*
> ```Go
> 	// Suspended condition doesn't exist, ref: https://kubernetes.io/docs/concepts/architecture/nodes/#node-status
> 	It("should expect powered off VM's node status to be NotReady", func() {
> 		err := tc.WaitForWorkerNodeNotReady(ctx, workerNode)
> ```

Is this function checking for both Ready condition False and Ready condition Unknown? Just curious.

Also how long does the function wait for the node to become not ready?
___
*[`tests/e2e/utils/cpi_vcd_utils.go` line 99 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMFhT0X6nnf-IloSCUO:-NMFhT0X6nnf-IloSCUP:b-669nmk) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/utils/cpi_vcd_utils.go#L99)):*
> ```Go
> 
> 	// All are present then this is a valid case
> 	if vsFound && lbPoolFound && dnatRuleFound && appPortProfileFound {
> ```

should we not check for if dnatRuleFound and appPortProfileFound are true only if oneArm is not nil ?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212)* status: 8 of 254 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, @rliang88, and @ymo24)

___
*[`tests/e2e/loadbalancer_test.go` line 90 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMBefsG8MHZBUfqLW2l:-NMGNybi4jkCt3jNMNrm:bvpr1mz) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/loadbalancer_test.go#L90)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

As discussed, can we move this function call to before Case 1 is defined?
</blockquote></details>

Updated, thanks Aniruddh!
___
*[`tests/e2e/loadbalancer_test.go` line 159 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMFR_Ei3UXZ8j0rfSBa:-NMGNlle2rS_H1DIcj7z:b-t6yof5) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/loadbalancer_test.go#L159)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Another question, what if there is an error in the execution? Will other tests continue to execute?
</blockquote></details>

The rest of the test suite will continue to execute and other `It()`'s, however for the test that it failed on it will not continue through the remainder of that test case. So currently there are 11 test cases, if there is an execution error in 1 of the test, that test will fail, and assuming all other tests pass, it will end up 10/11 tests passed
___
*[`tests/e2e/node_test.go` line 58 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMFT1AvBsFDufYc69l3:-NMGNRsfC8Lp22O50Do7:bsag09p) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/node_test.go#L58)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is this function checking for both Ready condition False and Ready condition Unknown? Just curious.

Also how long does the function wait for the node to become not ready?
</blockquote></details>

Yes, that function is checking the both Ready condition as False and Unknown, as it is checking against `condition.Status != apiv1.ConditionTrue`. It currently waits for 8 minutes
___
*[`tests/e2e/utils/cpi_vcd_utils.go` line 99 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMFhT0X6nnf-IloSCUO:-NMGQVHk3TMRo6WcZz8Z:b-8avyf8) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/39781431c14fab7070c9aba5d3d511b0bad9ee77/tests/e2e/utils/cpi_vcd_utils.go#L99)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should we not check for if dnatRuleFound and appPortProfileFound are true only if oneArm is not nil ?
</blockquote></details>

Yes you are correct, we should have that check as well. Thanks for the catch!

**Review by arunmk — APPROVED** [review]
:lgtm:
I mainly looked at code organization and interfaces and have a couple of comments there. I think Aniruddha already has looked in detail about the functionality

> Reviewed 19 of 254 files at r1, 1 of 5 files at r2, 2 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-:-NMVUBLy4IRGYtM7PfDR:bgttq9)* status: 27 of 254 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @lzichong, @rliang88, and @ymo24)

___
*[`tests/e2e/utils/service_utils.go` line 14 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMVTTlf-DsTXpfTPFZ1:-NMVTTlf-DsTXpfTPFZ2:b6ewkww) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8053561906ce9864147db295db84bbad57632d42/tests/e2e/utils/service_utils.go#L14)):*
> ```Go
> )
> 
> func WaitForExtIP(cs kubernetes.Interface, namespace string, name string) (string, error) {
> ```

Should this go into common-core?
___
*[`tests/e2e/utils/utils.go` line 28 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212#-NMVTkYlDswjHOibD29X:-NMVTkYlDswjHOibD29Y:bqu9p2m) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8053561906ce9864147db295db84bbad57632d42/tests/e2e/utils/utils.go#L28)):*
> ```Go
> )
> 
> func GetConfigMap(cs kubernetes.Interface, namespace, name string) (*v1.ConfigMap, error) {
> ```

Maybe all utils can go into common-core testing

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 254 files at r1, 3 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/212)* status: 27 of 256 files reviewed, 6 unresolved discussions (waiting on @lzichong, @rliang88, and @ymo24)

**Pull request merged**
