### PR TITLE
rl/VKCI-91

### PR DESCRIPTION
**Pull request by rliang88**
added `set_utils` file to `testingsdk`

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208)

### CODE REVIEW

**Review by lzichong — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208)* status: all files reviewed, 1 unresolved discussion (waiting on @rliang88 and @ymo24)

___
*[`pkg/testingsdk/set_utils.go` line 5 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208#-NLXoRZJ1ALsHLtJfdrd:-NLXnhOg5cFn92wrcoAu:b-ps2mu6) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/068bb5a24d9f25eb1ea311f0f59e4f31973af3c6/pkg/testingsdk/set_utils.go#L5)):*
> ```Go
> var exists = struct{}{}
> 
> type set struct {
> ```

Should this be exposed?

**Review by lzichong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208#-:-NLXonnA6GDE8pS1T3UR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rliang88 and @ymo24)

**Review by ymo24 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lzichong and @rliang88)

*[a discussion](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208#-NLXtZQb8CkH-VACRrh1:-NLXtZQc2trYzOHFLYF6:bg7igkv) (no related file):*
:lgtm: 

___

**Review by ymo24 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lzichong and @rliang88)

*[a discussion](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208#-NLXtZQb8CkH-VACRrh1:-NLXtjwG3shkI8ayytfj:b-8eqf7b) (no related file):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

:lgtm

___

**Review by lzichong — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/208)* status: all files reviewed, 3 unresolved discussions (waiting on @rliang88)

**Pull request merged**
