### PR TITLE
Set ComputerName as vmName

### PR DESCRIPTION
**Pull request by erkanerol**
Some users' naming policies enforce that the computer name matches the VM name.
This is also the default behavior in the VCD UI when provisioning a VM.
This PR replicates the default policy and sets the VM computerName field to the same values as the VM name.

This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/219)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/219#-:-NNbgucB1xDMFZ1ag5Sb:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Anirudh9794 and @ltimothy7)

**Review by Anirudh9794 — APPROVED** [review]
No, I don't. This looks good to me as well

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/219#-:-NNgpmwf-NyzsVO8AvyU:b-rnu5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Comment by erkanerol** [comment]
@ltimothy7 May I get the last approval for this PR?

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @erkanerol)

**Comment by erkanerol** [comment]
@arunmk Can you merge this PR?

**Pull request merged**
