### PR TITLE
[VKCI-82] Modify UpdateLoadBalancer() in gateway.go to include an IP address

### PR DESCRIPTION
**Pull request by Anirudh9794**
Changes:

- Accept an ip address as a parameter to update load balancer virtual service or dnat rule based on CPI configuration
- Add system tests to test the load balancer IP for UpdateLoadBalancer

Testing done:

- Ran system tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by arunmk — APPROVED** [review]
:lgtm:

1. Can we get Tim to review this as well
2. What happens if we error out n the case of enableSingle...

> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-:-NJBbAxt69rjUefLmQRE:b-ribm5e)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[`pkg/vcdsdk/gateway.go` line 1106 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-NJBVhNR4yP1cH9zXV5G:-NJBVhNR4yP1cH9zXV5H:bguauoc) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dc650c210e616488a34da4c5c4b8355fe6d28f67/pkg/vcdsdk/gateway.go#L1106)):*
> ```Go
> }
> 
> func (gatewayManager *GatewayManager) UpdateVirtualService(ctx context.Context, virtualServiceName string,
> ```

Nit: can we put the externalIP before externalPort since that's common (ip, port)
___
*[`pkg/vcdsdk/gateway.go` line 1869 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-NJBaqxy1M1KjXufoOjZ:-NJBaqxy1M1KjXufoOj_:b-g5fa8y) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dc650c210e616488a34da4c5c4b8355fe6d28f67/pkg/vcdsdk/gateway.go#L1869)):*
> ```Go
> 		return "", fmt.Errorf("configuration with enableVirtualServiceSharedIP [%v] and oneArm [%v] is not supported", enableVirtualServiceSharedIP, oneArm)
> 	}
> 	if !(enableVirtualServiceSharedIP && oneArm == nil) { // dnat not used if vsSharedIP is used and oneArm is nil
> ```

Can we get @ltimothy7 to review the cases below

**Review by ltimothy7 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-:-NJC2pCa8h8xLPuLDMI8:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[`pkg/vcdsdk/gateway.go` line 1107 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-NJC1VHf5-TkyVdKwMBp:-NJC1VHf5-TkyVdKwMBq:b-pyyac7) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dc650c210e616488a34da4c5c4b8355fe6d28f67/pkg/vcdsdk/gateway.go#L1107)):*
> ```Go
> 
> func (gatewayManager *GatewayManager) UpdateVirtualService(ctx context.Context, virtualServiceName string,
> 	externalPort int32, externalIP string, oneArmEnabled bool) (*swaggerClient.EntityReference, error) {
> ```

Using `vsIP` might be clearer

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[`pkg/vcdsdk/gateway.go` line 1107 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-NJC1VHf5-TkyVdKwMBp:-NJCkXew6zJaK2DPeqfH:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dc650c210e616488a34da4c5c4b8355fe6d28f67/pkg/vcdsdk/gateway.go#L1107)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Using `vsIP` might be clearer
</blockquote></details>

Done.
___
*[`pkg/vcdsdk/gateway.go` line 1869 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-NJBaqxy1M1KjXufoOjZ:-NJCkcxQ5JMQnRRmzGES:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dc650c210e616488a34da4c5c4b8355fe6d28f67/pkg/vcdsdk/gateway.go#L1869)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we get @ltimothy7 to review the cases below
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
> What happens if we error out n the case of enableSingle...
I discussed the above with Tim.
CPI won't start up if it is configured with enableVirtualServiceSharedIP: false & oneArm: nil

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/184#-:-NJCks1C9DO5XEcR1OHq:b-4gva1l)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @arunmk, @ltimothy7, and @lzichong)

**Pull request merged**
