### PR TITLE
CPI changes to use the updated capvcdCluster schema

### PR DESCRIPTION
**Pull request by Anirudh9794**
ticket : VCDA-3464

- Created go types for CPI section of capvcdCluster RDE
- change get and update methods which updates virtual IPs in the RDE

Sample CPI section:
```
"cpi": {
                "name": "cloud-controller-manager",
                "version": "1.1.2",
                "vcdResourceSet": [
                    {
                        "id": "b7a60dee-08cc-4814-bc2a-d727e63fb544",
                        "name": "dnat-ingress-vs-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-http",
                        "type": "dnat-rule"
                    },
                    {
                        "id": "urn:vcloud:loadBalancerPool:dfccb8fa-9d16-4bbe-93d8-b8d596f508c2",
                        "name": "ingress-pool-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-http",
                        "type": "lb-pool"
                    },
                    {
                        "id": "urn:vcloud:loadBalancerVirtualService:135827bc-f8f6-47b8-8329-97a0d040888f",
                        "name": "ingress-vs-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-http",
                        "type": "virtual-service",
                        "additionalDetails": {
                            "virtualIP": "10.150.161.78"
                        }
                    },
                    {
                        "id": "urn:vcloud:applicationPortProfile:c2065525-69c6-4851-8a93-ad77eb0fa484",
                        "name": "appPort_dnat-ingress-vs-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-http",
                        "type": "app-port-profile"
                    },
                    {
                        "id": "dda6e265-17e7-478a-849b-8d4663aaee44",
                        "name": "dnat-ingress-vs-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-https",
                        "type": "dnat-rule"
                    },
                    {
                        "id": "urn:vcloud:loadBalancerPool:53ac95e9-0b46-4511-9373-4ccc1c4eef17",
                        "name": "ingress-pool-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-https",
                        "type": "lb-pool"
                    },
                    {
                        "id": "urn:vcloud:loadBalancerVirtualService:63bea64a-ce4f-4083-aade-d7afbdb4df42",
                        "name": "ingress-vs-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-https",
                        "type": "virtual-service",
                        "additionalDetails": {
                            "virtualIP": "10.150.161.78"
                        }
                    },
                    {
                        "id": "urn:vcloud:applicationPortProfile:ae49b600-4510-42c8-8ed3-de2734bc8d86",
                        "name": "appPort_dnat-ingress-vs-ingress-nginx-controller-capvcdCluster:cf7e20e7-0400-4d92-9515-903a7386ae6e-https",
                        "type": "app-port-profile"
                    }
                ]
            }
```

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-:-MzaUpcM9Dgqhl3C83e_:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[pkg/util/defined_entity_util.go, line 109 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzaUfAu-m2nG7Rj279H:-MzaUfAu-m2nG7Rj279I:b-ndvpzh) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/62329af087e4edaf7f31812f311ab6cd1c90a744/pkg/util/defined_entity_util.go#L109)):*
> ```Go
> 	}
> 	if isCAPVCDEntityType(rde.EntityType) {
> 		// TODO: upgrade existing entities to capvcdCluster 1.1.0
> ```

Upgrade needs to happen at the start-up. Can you please spot the ideal place and add a TODO there?
___
*[pkg/util/defined_entity_util.go, line 111 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzaUHbd4wR8bp7elgDh:-MzaUHbe0NO8xwzcHW_T:b-yab12l) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/62329af087e4edaf7f31812f311ab6cd1c90a744/pkg/util/defined_entity_util.go#L111)):*
> ```Go
> 		// TODO: upgrade existing entities to capvcdCluster 1.1.0
> 		cpiStatusInterface, ok := statusMap["cpi"]
> 		var cpiStatusMap map[string]interface{}
> ```

Just curious to know, why we need this way of declaring the interface and then retrieving the map from it. Can't we do the below in the Go?

var cpiStatusMap map[string]interface{}
cpiStatusMap, ok = statusMap["cpi"]

Will the above fail?

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[pkg/util/defined_entity_util.go, line 111 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzaUHbd4wR8bp7elgDh:-MzaWO7K7I9q2W_93_Im:b7f4l9p) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/62329af087e4edaf7f31812f311ab6cd1c90a744/pkg/util/defined_entity_util.go#L111)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Just curious to know, why we need this way of declaring the interface and then retrieving the map from it. Can't we do the below in the Go?

var cpiStatusMap map[string]interface{}
cpiStatusMap, ok = statusMap["cpi"]

Will the above fail?
</blockquote></details>

btw, can't we simply cast the map into CPIStatus instance?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[pkg/util/defined_entity_util.go, line 23 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzaVn3V9uM_y63Zft0D:-MzqvldT2GrER52IsxTA:b-op2o5l) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/62329af087e4edaf7f31812f311ab6cd1c90a744/pkg/util/defined_entity_util.go#L23)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Where is this being used? We must construct the object and set a few properties like Name, and Version at someplace.
VCDResourceSet needs to be populated every time a virtual service gets created.
</blockquote></details>

Making use of this struct to update CPI status with Virtual service details
___
*[pkg/util/defined_entity_util.go, line 109 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzaUfAu-m2nG7Rj279H:-Mzqvvey8Lzo0fio-w4T:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/62329af087e4edaf7f31812f311ab6cd1c90a744/pkg/util/defined_entity_util.go#L109)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Upgrade needs to happen at the start-up. Can you please spot the ideal place and add a TODO there?
</blockquote></details>

Done.
___
*[pkg/util/defined_entity_util.go, line 111 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzaUHbd4wR8bp7elgDh:-MzqvxT0-jbkxv4koNvu:bjopk77) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/62329af087e4edaf7f31812f311ab6cd1c90a744/pkg/util/defined_entity_util.go#L111)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

btw, can't we simply cast the map into CPIStatus instance?
</blockquote></details>

As discussed offline, casting the map to CPIStatus and then converting it back to a map to update a single property seemed like an overkill.
So have followed the older approach of updating the map directly. Please let me know if this is not okay. I can change the approach just for CAPVCD entity types

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[pkg/ccm/cloud.go, line 109 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-Mzr9gS13SBZ1GykY7p1:-Mzr9gS13SBZ1GykY7p2:b-qe4gtd) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/ccm/cloud.go#L109)):*
> ```Go
> 	vmInfoCache := newVmInfoCache(vcdClient, time.Minute)
> 
> 	// TODO: upgrade all CAPVCD RDEs here
> ```

you can remove the TODO. And please add a comment that the below step upgrades the CPI sections of the existing RDEs.
___
*[pkg/vcdclient/rde.go, line 181 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzrCVvpBmb9oGPbA5k_:-MzrCVvpBmb9oGPbA5ka:bl5g0x1) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/vcdclient/rde.go#L181)):*
> ```Go
> }
> 
> func (client *Client) CreateOrUpdateCPIStatusInRDE(ctx context.Context, rdeId string) error {
> ```

Thanks Aniruddh for adding all of this right in this PR
Please add a detailed comment on when and why this method needs to be called.

This method currently updates the CPI section of the existing RDEs to the latest model. 
CPI 1.1.2, as this section is empty in all the older existing RDEs, will always create a new section.
But the future versions of CPI need to compare CPIStatus.Version property in the existing RDEs to determine whether an RDEupgrade is needed. Future behavior also needs to be readily understood by the readers.

Consider renaming this method to upgradeCPIStatusOfExistingRDE(). And then, extract the entire logic to another convertFromCPIVersionXYZ() (or) convertFromLegacyCPI()method. In the future more convertFromCPIVersionXYZ() methods may get added. Put these methods in the respective Go types file.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[pkg/vcdclient/rde.go, line 189 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-Mzs3_3L9q9vHl3s2xBx:-Mzs3_3L9q9vHl3s2xBy:b-irp872) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/vcdclient/rde.go#L189)):*
> ```Go
> 		}
> 		return fmt.Errorf(
> 			"failed to get RDE with id [%s]; expected http response [%v], obtained [%v]: resp: [%#v]: [%v]",
> ```

Can you please add more context to all the log statements? 

For example, reading the above statement from the CPI logs will not provide enough context that something about RDE failed during the "upgrade" step. Please add the context of the upgradeRDE in all the error log statements of this method -"failed to retrieve RDE during the upgrade of the CPIStatus section of the existing RDE".

Troubleshooting is one of the big items Customers struggle with. 
___
*[pkg/vcdclient/rde.go, line 253 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-Mzs4cY68AsxphGyQiUY:-Mzs4cY68AsxphGyQiUZ:bgttxvk) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/vcdclient/rde.go#L253)):*
> ```Go
> 		}
> 		return fmt.Errorf(
> 			"failed to get RDE with id [%s]; expected http response [%v], obtained [%v]: resp: [%#v]: [%v]",
> ```

Same here, please update the log statements wherever relevant with some more context - "while adding VS to VCDResourceSet".

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[pkg/ccm/cloud.go, line 109 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-Mzr9gS13SBZ1GykY7p1:-MzvZYLm6kR5YjHgs4gG:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/ccm/cloud.go#L109)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

you can remove the TODO. And please add a comment that the below step upgrades the CPI sections of the existing RDEs.
</blockquote></details>

Done.
___
*[pkg/vcdclient/rde.go, line 181 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-MzrCVvpBmb9oGPbA5k_:-MzvTmuK3Eb9pYAGN70F:bdw3822) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/vcdclient/rde.go#L181)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Thanks Aniruddh for adding all of this right in this PR
Please add a detailed comment on when and why this method needs to be called.

This method currently updates the CPI section of the existing RDEs to the latest model. 
CPI 1.1.2, as this section is empty in all the older existing RDEs, will always create a new section.
But the future versions of CPI need to compare CPIStatus.Version property in the existing RDEs to determine whether an RDEupgrade is needed. Future behavior also needs to be readily understood by the readers.

Consider renaming this method to upgradeCPIStatusOfExistingRDE(). And then, extract the entire logic to another convertFromCPIVersionXYZ() (or) convertFromLegacyCPI()method. In the future more convertFromCPIVersionXYZ() methods may get added. Put these methods in the respective Go types file.



</blockquote></details>

Done. Moved `UpgradeCPIStatusOfExistingRDE()` `AddVirtualServiceToVCDResourceSet()` `RemoveVirtualServiceFromVCDResourceSet()` to `cpi_rde_1_1_2.go`
___
*[pkg/vcdclient/rde.go, line 189 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-Mzs3_3L9q9vHl3s2xBx:-MzvZ9k78KNhtKcuFmRm:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/vcdclient/rde.go#L189)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you please add more context to all the log statements? 

For example, reading the above statement from the CPI logs will not provide enough context that something about RDE failed during the "upgrade" step. Please add the context of the upgradeRDE in all the error log statements of this method -"failed to retrieve RDE during the upgrade of the CPIStatus section of the existing RDE".

Troubleshooting is one of the big items Customers struggle with. 
</blockquote></details>

Done.
___
*[pkg/vcdclient/rde.go, line 253 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-Mzs4cY68AsxphGyQiUY:-MzvZ8DcBvhH4iQ0nVA2:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/a141a03886a8544c89bea4658a74853b198f6945/pkg/vcdclient/rde.go#L253)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same here, please update the log statements wherever relevant with some more context - "while adding VS to VCDResourceSet".
</blockquote></details>

Done.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: 0 of 7 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[pkg/util/defined_entity_util.go, line 17 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-Nfq_uECYz3fC0CQG2:-N-Nfq_vA7_Ulu4goJ_6:bxs3jvi) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/util/defined_entity_util.go#L17)):*
> ```Go
> )
> 
> type CapvdRdeFoundError struct {
> ```

nit: typo
___
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 77 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-NhuGZ2nLLph86_jrk:-N-NhuGZ2nLLph86_jrl:bxkaiue) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/vcdclient/cpi_rde_1_1_2.go#L77)):*
> ```Go
> 		if err != nil {
> 			return nil, fmt.Errorf("failed to convert CPI status map in RDE to CPI status object: [%v]", err)
> 		}
> ```

Is return statement missing in this if block? if a valid cpi section is found, return?
___
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 91 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-NgJin-ln8kb1qyPS1:-N-NgJin-ln8kb1qyPS2:b-w2zttx) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/vcdclient/cpi_rde_1_1_2.go#L91)):*
> ```Go
> 
> // UpgradeCPIStatusOfExistingRDE Creates an empty cpi section with just the name and version populated if CPI status
> // section is missing from CAPVCD RDE
> ```

You can also add below to the comment
- "The rest of the content is lazily filled in by the reconcile method of ...."
- When is this method supposed to be called? 
- For future CPI upgrades, this method may become a factory of converters (ConvertFrom()).
___
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 93 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-NgfsQ4fDXPPeymET-:-N-NgfsQ4fDXPPeymET0:bs3w0mf) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/vcdclient/cpi_rde_1_1_2.go#L93)):*
> ```Go
> // section is missing from CAPVCD RDE
> func (client *Client) UpgradeCPIStatusOfExistingRDE(ctx context.Context, rdeId string) error {
> 	klog.Infof("upgrading CPI section in RDE")
> ```

Please add RDE Id to the log statement.
___
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 195 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-NlMTfDZkprvoKxmn9:-N-NlMTfDZkprvoKxmnA:b-j52w1t) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/vcdclient/cpi_rde_1_1_2.go#L195)):*
> ```Go
> }
> 
> func (client *Client) AddToVCDResourceSet(ctx context.Context, resourceType string, resourceName string, resourceId string, additionalDetails map[string]interface{}) error {
> ```

Aniruddh, can we make this method and other relevant methods generic enough so that they can be reused in CSI, CAPVCD, and VKP as well? I think by allowing this method to take another param about - "which section (cpi, capvcd, csi, vkp) it is supposed to add the VCD resource to", we can make it generic. Let me know if you see any issues.

We can then move them into a new file of rdeStatusUpdateUtils.go of common CPI library code.

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 6 files at r5, 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: 3 of 7 files reviewed, 16 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[pkg/util/defined_entity_util.go, line 73 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-8mHi39p456c5CHNbo:-N-8mHi39p456c5CHNbp:b-cqj1u) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/util/defined_entity_util.go#L73)):*
> ```Go
> 			EntityType: rde.EntityType,
> 		}
> 		return nil, capvcdEntityFoundErr
> ```

Just a go-style thing, we could also return:
```
return nil, CapvdRdeFoundError{
			EntityType: rde.EntityType,
		}
```
___
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 1 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-8mfIn6XWucKtUv4fa:-N-8mfIn6XWucKtUv4fb:bqs243q) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/vcdclient/cpi_rde_1_1_2.go#L1)):*
> ```Go
> package vcdclient
> ```

The version is not yet known, but generally any rde structure change is at the very least a .y change. A .z change is never for features and only for bugfixes (https://semver.org/)
___
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 231 at r7](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-eIw3f2Xd0uts_yjlD:-N-eIw3f2Xd0uts_yjlE:b3zgjii) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8b0281b1f7dfdfd16f05bc230aa265fe88a636a3/pkg/vcdclient/cpi_rde_1_1_2.go#L231)):*
> ```Go
> 		AdditionalDetails: additionalDetails,
> 	}
> 	updatedStatusMap, err := AddToVCDResourceSet(statusMap, vcdResource)
> ```

There needs to be a loop to ensure that there are no ETag failures during update. Same with RemoveFrom... function
___
*[pkg/vcdclient/gateway.go, line 535 at r7](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-eLbRQ-R-k8Ri4zwX8:-N-eLbRQ-R-k8Ri4zwX9:b-g0ee6k) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8b0281b1f7dfdfd16f05bc230aa265fe88a636a3/pkg/vcdclient/gateway.go#L535)):*
> ```Go
> 	}
> 	// update RDE
> 	if err := client.AddToVCDResourceSet(ctx, VcdResourceDNATRule, dnatRuleRef.Name, dnatRuleRef.ID, nil); err != nil {
> ```

There could be a retry loop and we may be adding to the RDE again here. But that should be fine I think.
___
*[pkg/vcdclient/gateway.go, line 1171 at r7](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-eMJrH4S1O4LYopWZ5:-N-eMJrH4S1O4LYopWZ6:b-8n7ynu) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8b0281b1f7dfdfd16f05bc230aa265fe88a636a3/pkg/vcdclient/gateway.go#L1171)):*
> ```Go
> 
> 	// update RDE
> 	virtualIPDetails := map[string]interface{}{
> ```

Nit: this can be directly passed by value to the AddToVCDResourceSet function

**Comment by arunmk** [comment]
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 1 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-8mfIn6XWucKtUv4fa:-N-eOhyLBkCLmFbsK755:b-mo9cxc) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/vcdclient/cpi_rde_1_1_2.go#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

The version is not yet known, but generally any rde structure change is at the very least a .y change. A .z change is never for features and only for bugfixes (https://semver.org/)
</blockquote></details>

Let us call this a 1.2 at least.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62)* status: 2 of 7 files reviewed, 16 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[pkg/util/defined_entity_util.go, line 73 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-8mHi39p456c5CHNbo:-N-fHSlx-1hKY7wbYyhN:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/util/defined_entity_util.go#L73)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Just a go-style thing, we could also return:
```
return nil, CapvdRdeFoundError{
			EntityType: rde.EntityType,
		}
```

</blockquote></details>

Done.
___
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 1 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-8mfIn6XWucKtUv4fa:-N-fItiZEPLb6dMPh3RV:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0527457e51a763e729ebd582f8688dae9f94222b/pkg/vcdclient/cpi_rde_1_1_2.go#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Let us call this a 1.2 at least.
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
*[pkg/vcdclient/cpi_rde_1_1_2.go, line 231 at r7](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-eIw3f2Xd0uts_yjlD:-N-jP9HY4sdzvMKI5fVq:b-896fjx) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8b0281b1f7dfdfd16f05bc230aa265fe88a636a3/pkg/vcdclient/cpi_rde_1_1_2.go#L231)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

There needs to be a loop to ensure that there are no ETag failures during update. Same with RemoveFrom... function
</blockquote></details>

Done

**Comment by Anirudh9794** [comment]
*[pkg/vcdclient/gateway.go, line 535 at r7](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/62#-N-eLbRQ-R-k8Ri4zwX8:-N-jPEKHDkKuQg4Um919:byhfxjp) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8b0281b1f7dfdfd16f05bc230aa265fe88a636a3/pkg/vcdclient/gateway.go#L535)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

There could be a retry loop and we may be adding to the RDE again here. But that should be fine I think.
</blockquote></details>

Done. Included the retry loop within AddTo... and RemoveFrom.... functions

**Pull request merged**
