### PR TITLE
[VKCI-160] CPI 1.4.0 Documentation

### PR DESCRIPTION
**Pull request by ltimothy7**
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/248)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/248)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/248#-NTFUKwA0abk7rX2R--d:-NTFUKwA0abk7rX2R--e:b-lcl8i6) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/463ff3ce28d876d1336236eb2bdab73b685a8e7e/README.md#L8)):*
> ```Markdown
> | CPI Version | CSE Version | VMware Cloud Director API | VMware Cloud Director Installation | Notes | Kubernetes Versions | docs |
> | :---------: | :---------: | :-----------------------: | :--------------------------------: | :---: | :------------------ | :--: |
> | 1.4.0 | 4.0.0+ | 36.0 | 10.3.1+ <br/>(10.3.1 needs hot-patch to prevent VCD cell crashes in multi-cell environments) | <ul><li>Support for packaging CPI CRS in a container for CSE airgap workflow.</li><li>Bug fixes: safe access for OVDC, safe access for OVDC network, setting computer name as vm name.</li></ul> |<ul><li>1.23</li><li>1.22</li><li>1.21</li><li>1.20</li></ul>|[CPI 1.4.z docs](https://github.com/vmware/cloud-provider-for-cloud-director/tree/1.4.z)|
> ```

I don't know if this was a bug.
https://github.com/vmware/cloud-provider-for-cloud-director/pull/219  says that this is to make it in line with what users follow as a practice.
Can you please verify if this can be mentioned as a bug?



_Code quote:_
```Markdown
setting computer name as vm name
```

**Comment by ltimothy7** [comment]
*[`README.md` line 8 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/248#-NTFUKwA0abk7rX2R--d:-NTGQVgXEVMZOaue07e_:b6dqby5) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/463ff3ce28d876d1336236eb2bdab73b685a8e7e/README.md#L8)):*
> #219
Thank you for bringing this up. I viewed this as a bug because the PR mentioned: "Some users' naming policies enforce that the computer name matches the VM name." In this case, it could be a bug, I think. @arunmk let us know if you have input on this.

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/248)* status: 0 of 1 files reviewed, 1 unresolved discussion

**Comment by ltimothy7** [comment]
*[`README.md` line 8 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/248#-NTFUKwA0abk7rX2R--d:-NYU1JN65BOQOKJeZxlV:bdnr5fd) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/463ff3ce28d876d1336236eb2bdab73b685a8e7e/README.md#L8)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

> #219
Thank you for bringing this up. I viewed this as a bug because the PR mentioned: "Some users' naming policies enforce that the computer name matches the VM name." In this case, it could be a bug, I think. @arunmk let us know if you have input on this.
</blockquote></details>

Thank you; I have checked with Arun and updated setting the computer name as not a bug fix

**Pull request merged**
