### PR TITLE
[VCDA-2892] update RDE with external vip

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/9)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/9)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[pkg/vcdclient/gateway.go, line 378 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/9#-MjHehfo-1-dNmqAf2c-:-MjHehfo-1-dNmqAf2c0:b-k6k13y) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/10de27df767fc7e7e2c3c5d87f48d34bba6d1912/pkg/vcdclient/gateway.go#L378)):*
> ```Go
> }
> 
> func createDNATRuleName(virtualServiceName string) string {
> ```

Nice job!
___
*[pkg/vcdclient/gateway.go, line 1022 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/9#-MjHg5aw3Zy-ouyqRJM5:-MjHg5aw3Zy-ouyqRJM6:b-aea6ta) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/10de27df767fc7e7e2c3c5d87f48d34bba6d1912/pkg/vcdclient/gateway.go#L1022)):*
> ```Go
> 
> 		// get external IP
> 		dnatRuleName := createDNATRuleName(virtualServiceName)
> ```

This will always work but it is not necessary that we have a dnat rule. We will have one only if oneArm is not nil. So we need to do a check similar to when we created the dnat rule (`if client.OneArm != nil`)

**Comment by ltimothy7** [comment]
___
*[pkg/vcdclient/gateway.go, line 1022 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/9#-MjHg5aw3Zy-ouyqRJM5:-MjLpdMV29dZpwm0w0KV:b-sf12fd) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/10de27df767fc7e7e2c3c5d87f48d34bba6d1912/pkg/vcdclient/gateway.go#L1022)):*
> ```
> var err error
> ```
Thanks for the catch Arun

**Comment by arunmk** [comment]
:lgtm:

**Review by arunmk — APPROVED** [review]
Thanks Tim!

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/9#-:-MjLqnU9AmqJgkh6QGx4:b-y4s0bp)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

**Pull request merged**
