### PR TITLE
[VCDA-4387 ]Add retry logic to upgrade CPI section of existing RDE

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

Add retry logic to UpgradeCPISectionInStatus function and make a hard failure if the upgrade fail

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127)

### CODE REVIEW

**Review by ymo24 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/cpisdk/rde.go` line 305 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127#-NBtcbLR4UYb_aKmSvaa:-NBtcbLSBHNh2xcM0zEf:b-hqits9) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/693ea5d70f352a36f389eca53a0876ee3422a8fa/pkg/cpisdk/rde.go#L305)):*
> ```Go
> 		if resp != nil && resp.StatusCode != http.StatusOK {
> 			var responseMessageBytes []byte
> 			if gsErr, ok := err.(swaggerClient.GenericSwaggerError); ok {
> ```

Should we only consider retry when we get status code 412?
GenericSwaggerError accepts any status code



_Code quote:_
```Go
GenericSwaggerError
```

**Review by ymo24 — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

**Comment by Anirudh9794** [comment]
*[`pkg/cpisdk/rde.go` line 305 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127#-NBtcbLR4UYb_aKmSvaa:-NCQojHt8QXM3nZ99kZJ:bb5qz70) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/693ea5d70f352a36f389eca53a0876ee3422a8fa/pkg/cpisdk/rde.go#L305)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Should we only consider retry when we get status code 412?
GenericSwaggerError accepts any status code
</blockquote></details>

After discussion, we decided that retrying on every error will be better. So will be keeping this code as is.

**Review by arunmk — APPROVED** [review]
:lgtm: with one important question

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127#-:-NCRPhgy0nswHhEvkbZh:b-ol6nmf)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`pkg/cpisdk/rde.go` line 287 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127#-NCRPLYE8fl03w0Z7nFj:-NCRPLYE8fl03w0Z7nFk:b7e0j31) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/693ea5d70f352a36f389eca53a0876ee3422a8fa/pkg/cpisdk/rde.go#L287)):*
> ```Go
> 		}
> 
> 		statusEntity, ok := rde.Entity["status"]
> ```

if empty, should it create the empty status like the description of the function mentions?
___
*[`pkg/cpisdk/rde.go` line 308 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127#-NCROpk3040DrWIclzuY:-NCROpk3040DrWIclzuZ:b-gosvh3) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/693ea5d70f352a36f389eca53a0876ee3422a8fa/pkg/cpisdk/rde.go#L308)):*
> ```Go
> 				responseMessageBytes = gsErr.Body()
> 			}
> 			klog.Errorf(
> ```

If we are not throwing an error, better to make it a `Warnf`
___
*[`pkg/cpisdk/rde.go` line 313 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127#-NCROvpdDBW0Mcj3y-Mb:-NCROvpdDBW0Mcj3y-Mc:buo9nmt) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/693ea5d70f352a36f389eca53a0876ee3422a8fa/pkg/cpisdk/rde.go#L313)):*
> ```Go
> 			continue
> 		} else if err != nil {
> 			klog.Errorf("error while getting the RDE [%s]: [%v]. Remaining retry attempts: [%d]", rdeId, err, vcdsdk.MaxRDEUpdateRetries-retries+1)
> ```

Same here

**Comment by Anirudh9794** [comment]
*[`pkg/cpisdk/rde.go` line 287 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127#-NCRPLYE8fl03w0Z7nFj:-NCRQE0PBhlV4ERL0j_T:bu76vdj) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/693ea5d70f352a36f389eca53a0876ee3422a8fa/pkg/cpisdk/rde.go#L287)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

if empty, should it create the empty status like the description of the function mentions?
</blockquote></details>

The status part of the RDE is expected to be created by VCD. So the "status" section should be present when CPI is updating the RDE here.

**Pull request merged**
