### PR TITLE
[VCDA-4543] Misleading errors in CSE 4.0 logs regarding refreshToken failures

### PR DESCRIPTION
**Pull request by ymo24**
* Change message errors in CSE 4.0 logs regarding refreshToken failures
* CPI version name contains "1.2.z\n" because we have an extra line in version file. I have removed it.

Signed-off-by: ymo24 <ymo@vmware.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150)

### CODE REVIEW

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`release/version` line 1 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150#-NEcf30J-ejXAt4bCpNZ:-NEdL_y76GaFjNVFHGWw:b-q94cnc) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1375db176ef0f91559c5b4e39412fbdab00547df/release/version#L1)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

new line missing?
</blockquote></details>

Current version for CPI is "1.2.z\n". So I changed that

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @ymo24)

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/vcdsdk/auth.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150#-NEcebx_7V8gHdbUxMaw:-NEm7ZKD4vty7AYCAcfa:b-rzng7l) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1375db176ef0f91559c5b4e39412fbdab00547df/pkg/vcdsdk/auth.go#L53)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can we add the error message here ? There was a customer who was facing authentication issue for a system administrator user. The error message here can help us debug better.
</blockquote></details>

We might better remove the error message. Because if customers try to create cluster using a tenant account.Our customer must hit this error, which is expected. After this step, we will authenticate token as org user, we can log error message after authentication failed using org user.

**Review by arunmk — APPROVED** [review]
:lgtm: with some nits

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150#-:-NEwBdMX1__b9qhCoV0C:b-af439h)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`pkg/vcdsdk/auth.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150#-NEcebx_7V8gHdbUxMaw:-NEwB2LY5Bhru_EhJyZv:b-z4aeki) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1375db176ef0f91559c5b4e39412fbdab00547df/pkg/vcdsdk/auth.go#L53)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

We might better remove the error message. Because if customers try to create cluster using a tenant account.Our customer must hit this error, which is expected. After this step, we will authenticate token as org user, we can log error message after authentication failed using org user.
</blockquote></details>

Logging the `err` variable will be helpful I think
___
*[`pkg/vcdsdk/defined_entity.go` line 378 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150#-NEwBQqr4LwgR3DIl1iE:-NEwBQqr4LwgR3DIl1iF:b-jleyko) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d01a962ec5722f156c281f94953b5b384abd2a4d/pkg/vcdsdk/defined_entity.go#L378)):*
> ```Go
> 		if resp != nil {
> 			if resp.StatusCode == http.StatusPreconditionFailed {
> 				klog.V(4).Infof("wrong etag while removing error(s) of name [%s] in RDE [%s]. Retry attempts remaining: [%d]", errorName, rdeManager.ClusterID, i-1)
> ```

can we replace `wrong etag while...` with `etag mismatch while...`

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/vcdsdk/auth.go` line 53 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150#-NEcebx_7V8gHdbUxMaw:-NFExJp-ALd-pmSF-7h_:bn513dw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/1375db176ef0f91559c5b4e39412fbdab00547df/pkg/vcdsdk/auth.go#L53)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Logging the `err` variable will be helpful I think
</blockquote></details>

Thanks Arun and Aniruddha, I have pushed the change
___
*[`pkg/vcdsdk/defined_entity.go` line 378 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/150#-NEwBQqr4LwgR3DIl1iE:-NFExIyEAajujx271eDx:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d01a962ec5722f156c281f94953b5b384abd2a4d/pkg/vcdsdk/defined_entity.go#L378)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

can we replace `wrong etag while...` with `etag mismatch while...`
</blockquote></details>

Done.

**Pull request merged**
