### PR TITLE
[VKCI-61] Use user specified load balancer IP for application load balancer

### PR DESCRIPTION
**Pull request by Anirudh9794**
use user specified load balancer IP to create Load Balancer in VCD
```
apiVersion: v1
kind: Service
  name: ingress-nginx-controller
  namespace: default
spec:
  loadBalancerIP: 10.221.134.21
  type: LoadBalancer
 ...
```
In the above example, the IP `10.221.134.21` should be used for
1. Virtual service VIP if `oneArm` is `nil`  in the cloud provider config map
2. DNAT rule external IP if `oneArm` is not `nil` 

Testing done:
1. Configure CPI with `ensureVirtualServiceSharedIP: true` and `oneArm: nil`. Create ingress with `loadBalancerIP` set.
2. Configure CPI with `ensureVirtualServiceSharedIP: true` and `oneArm` specified. Create ingress with `loadBalancerIP` set.
3. Configure CPI with `ensureVirtualServiceSharedIP: false` and `oneArm` specified. Create an application LB with `loadBalancerIP` set.
4. Create application LB with `loadBalancerIP` not set.

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm:, though should the `.cloud-director-ccm-yaml.swp` file be there?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180#-:-NIdbZxVC6nAaNOQAfuT:bkpp01k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arunmk and @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/ccm/loadbalancer.go` line 487 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180#-NIdkL3vDdJkXPz5PiGb:-NIdkL3vDdJkXPz5PiGc:b-rlrywk) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/11b3ea01c5bab4d6fb0b756edeb42340cac0ae05/pkg/ccm/loadbalancer.go#L487)):*
> ```Go
> 
> func getUserSpecifiedLoadBalancerIP(service *v1.Service) string {
> 	return service.Spec.LoadBalancerIP
> ```

Is this empty or nil if not present?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @ltimothy7)

___
*[`pkg/ccm/loadbalancer.go` line 487 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180#-NIdkL3vDdJkXPz5PiGb:-NIiDvrz3GHEdN-xSdFv:btmlvcd) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/11b3ea01c5bab4d6fb0b756edeb42340cac0ae05/pkg/ccm/loadbalancer.go#L487)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Is this empty or nil if not present?
</blockquote></details>

LoadBalancerIP is defined as a string. So, it cannot be nil. If it is empty, the empty string is passed down to CreateLoadBalancer() in gateway.go, which will use one of the allocated IPs from the edge gateway

**Comment by ltimothy7** [comment]
*[`pkg/ccm/loadbalancer.go` line 487 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180#-NIdkL3vDdJkXPz5PiGb:-NIsG5-L3dJrvzYtN11O:b-trshvt) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/11b3ea01c5bab4d6fb0b756edeb42340cac0ae05/pkg/ccm/loadbalancer.go#L487)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

LoadBalancerIP is defined as a string. So, it cannot be nil. If it is empty, the empty string is passed down to CreateLoadBalancer() in gateway.go, which will use one of the allocated IPs from the edge gateway
</blockquote></details>

Could you make a comment for this for easier readability?

**Review by ltimothy7 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180#-:-NIsGBH19RVYIGsllrSV:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

**Comment by Anirudh9794** [comment]
*[`pkg/ccm/loadbalancer.go` line 487 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180#-NIdkL3vDdJkXPz5PiGb:-NIsm3R_40y-9Jx_vVXI:bb6un1j) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/11b3ea01c5bab4d6fb0b756edeb42340cac0ae05/pkg/ccm/loadbalancer.go#L487)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Could you make a comment for this for easier readability?
</blockquote></details>

Done

**Review by arunmk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/180#-:-NJ74pQX9VV2Vz1sZR6E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Pull request merged**
