### PR TITLE
Move functions from vcdclient in CAPVCD  to vcdsdk in CPI

### PR DESCRIPTION
**Pull request by Anirudh9794**
ticket: VCDA-3528
Changes:
* Functions specific to CPI are moved to vcdcpiclient package
* Added functions from vcdclient from CAPVCD to vcdsdk in CPI

Testing:
* create docker image using `make ccm`
* nginx and shapes test

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65)* status: 0 of 18 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/vcdsdk/org.go` line 1 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aJr_R0GNvGb37bDko:-N0aJr_S1Jq5olFBSAKX:bq7bk78) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/org.go#L1)):*
> ```Go
> package vcdsdk
> ```

This vcdsdk package can also contain all RDE management files and resourceset files. Are you planning to do that in a different PR?
___
*[`pkg/vcdsdk/org.go` line 16 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aIqI40yA2Jeo3-u_c:-N0aIqI40yA2Jeo3-u_d:b-fpscrb) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/org.go#L16)):*
> ```Go
> }
> 
> func NewOrgManager(client *Client) *OrgManager{
> ```

This also needs to take orgName as a param.
How does this work in the case of Sysadmin case. 
___
*[`pkg/vcdsdk/org.go` line 25 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aJ8910O-E1AGfgkSI:-N0aJ8910O-E1AGfgkSJ:bc1vcah) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/org.go#L25)):*
> ```Go
> 	org, err := orgManager.Client.VCDClient.GetOrgByName(orgManager.Client.ClusterOrgName)
> 	if err != nil {
> 		return nil, fmt.Errorf("unable to get vcd organization [%s]: [%v]", orgManager.Client.ClusterOrgName, err)
> ```

What is ClusterOrgName?
Is this LoggedInOrgName (or) the tenantOrgName?
How does this work in the sysadmin case?
___
*[`pkg/vcdsdk/vapp.go` line 23 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aFPfY-E973HIwvYov:-N0aFPfY-E973HIwvYow:b-yyhr9g) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/vapp.go#L23)):*
> ```Go
> }
> 
> func NewVDCManager(client *Client) (*VdcManager,error) {
> ```

vdcManager need to take vdcName as a param at the least.

If you are naming it VDCManager (instead of vAppManager), then there is no need for a separate VMManager.
I suggest referencing VM methods also to VDCManager to keep it simple. 

Both the managers need exactly the same details - client and vdcName. You can check CAPVCD files for reference. Do let me know if there is a need to keep them separate. 
___
*[`pkg/vcdsdk/vms.go` line 37 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aBd1w8y4RuGCo_wrh:-N0aBd1w8y4RuGCo_wri:b-fvspot) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/vms.go#L37)):*
> ```Go
> }
> 
> func NewVMManager(client *Client, clusterVAppName string) *VMManager {
> ```

Client and vAppName are not sufficient to create a VM. VDC details are required as well.
Please take VdcName also as a param and then populate VDC object.

I understand that the current client has a VDC object, but that needs to be used as just a fallback. 

Please add a VDC object (in the struct); it can be populated from the vdcname using the below reference logic. Orgname can be retrieved from the client.VcdAuthConfig. If vdcName is empty then fallback to client.VDC 


```
func (vdc *VdcManager) CacheVdcDetails() error {

	vcdClient, err := vdc.Client.VcdAuthConfig.GetPlainClientFromSecrets()
	if err != nil {
		return fmt.Errorf("unable to get plain client from secrets: [%v]", err)
	}

	org, err := vcdClient.GetOrgByName(vdc.OrgName)
	if err != nil {
		return fmt.Errorf("unable to get org from name [%s]: [%v]", vdc.OrgName, err)
	}

	vdc.Vdc, err = org.GetVDCByName(vdc.VdcName, true)
	if err != nil {
		return fmt.Errorf("unable to get Vdc [%s] from org [%s]: [%v]", vdc.VdcName, vdc.OrgName, err)
	}
	return nil
}
```

**Review by arunmk — CHANGES_REQUESTED** [review]
Thanks for doing this. It's not an easy task :)

Did all of the tests run well?

I have some concerns about removal of the RDE code. The rest is covered by other existing comments.

> Reviewed 4 of 17 files at r1, 3 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-:-N0b7laEDfT0N7mcYC4c:bm35zps)* status: 7 of 18 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`pkg/ccm/cloud.go` line 93 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0b78Yb1eOwVvtc5FAq:-N0b78Yb1eOwVvtc5FAr:brsmq9a) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/ccm/cloud.go#L93)):*
> ```Go
> 	} else {
> 		lb = newLoadBalancer(vcdClient, cloudConfig.LB.CertificateAlias, &vcdsdk.OneArm{
> 			StartIP: cloudConfig.LB.OneArm.StartIP,
> ```

we need to be sure that `cloudConfig.LB.OneArm` is not nil. So far we have tried to keep OneArm optional in the code at least.
___
*[`pkg/vcdcpiclient/cpi_gateway_manager_system_test.go` line 10 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0b8RI0BJK_Qr8ox5qs:-N0b8RI0BJK_Qr8ox5qt:b-bij5pc) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdcpiclient/cpi_gateway_manager_system_test.go#L10)):*
> ```Go
> 	"github.com/stretchr/testify/require"
> 	"github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk"
> 	_ "github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk"
> ```

this is extra, correct? 
___
*[`pkg/vcdsdk/auth_system_test.go` line 70 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bA-frA34TWyHj5nbI:-N0bA-frA34TWyHj5nbJ:b-jbr1uo) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/auth_system_test.go#L70)):*
> ```Go
> 
> 	vcdClient, err = GetTestVCDClient(cloudConfig, map[string]interface{}{
> 		"oneArm":  nil,
> ```

ok, this test should catch the nil oneArm that I asked above
___
*[`pkg/vcdsdk/gateway.go` line 166 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bACTZ8k4LPZ-rYSbV:-N0bACTZ8k4LPZ-rYSbW:b-5ieuu9) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/gateway.go#L166)):*
> ```Go
> 
> 	if oneArm == nil {
> 		return "", fmt.Errorf("unable to get unused external IP address as oneArm is nil")
> ```

unused _internal_ IP
___
*[`pkg/vcdsdk/gateway.go` line 1267 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bAVOSEPmrXq5TUFCR:-N0bAVOSEPmrXq5TUFCS:b-unn0h) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/924d602404252679e3e7e420e185e8098ab0a1e8/pkg/vcdsdk/gateway.go#L1267)):*
> ```Go
> 	}
> 
> 	// update RDE with freeIp
> ```

 I see the TODO above. Is this functionality done someplace else?
___
*[`pkg/vcdsdk/gateway.go` line 1403 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bAf_o5mA7tmu9as_e:-N0bAf_o5mA7tmu9as_f:b-op8bu) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/gateway.go#L1403)):*
> ```Go
> }
> 
> // CAPVCD code -------
> ```

What is this comment about?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65)* status: 7 of 18 files reviewed, 11 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`pkg/ccm/cloud.go` line 93 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0b78Yb1eOwVvtc5FAq:-N0blwi1AnRNXBC9mb3w:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/ccm/cloud.go#L93)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

we need to be sure that `cloudConfig.LB.OneArm` is not nil. So far we have tried to keep OneArm optional in the code at least.
</blockquote></details>

Done.
___
*[`pkg/vcdcpiclient/cpi_gateway_manager_system_test.go` line 10 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0b8RI0BJK_Qr8ox5qs:-N0bmlc57Hbwyhg3ekjU:b-6pl26g) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdcpiclient/cpi_gateway_manager_system_test.go#L10)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

this is extra, correct? 
</blockquote></details>

Yes, I removed it
___
*[`pkg/vcdsdk/auth_system_test.go` line 70 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bA-frA34TWyHj5nbI:-N0bmu_b-j766bPFHReA:b-8fx2u7) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/auth_system_test.go#L70)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

ok, this test should catch the nil oneArm that I asked above
</blockquote></details>

:+1: 
___
*[`pkg/vcdsdk/gateway.go` line 166 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bACTZ8k4LPZ-rYSbV:-N0bn51XEa2OG6Mw5YTY:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/gateway.go#L166)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

unused _internal_ IP
</blockquote></details>

Done.
___
*[`pkg/vcdsdk/gateway.go` line 1267 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bAVOSEPmrXq5TUFCR:-N0bn7P0Aiw0GCTw-fCQ:b-o48dhp) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/924d602404252679e3e7e420e185e8098ab0a1e8/pkg/vcdsdk/gateway.go#L1267)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

 I see the TODO above. Is this functionality done someplace else?
</blockquote></details>

Yes, I moved CPI specific implementations like CreateLoadBalancer, GetLoadBalancer and UpdateLoadBalancer to `vcdcpiclient/cpi_gateway_manager.go`
___
*[`pkg/vcdsdk/gateway.go` line 1403 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0bAf_o5mA7tmu9as_e:-N0bnSdT9PgzFTdAXbZ5:b-wm8q3l) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/gateway.go#L1403)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

What is this comment about?
</blockquote></details>

This is a stray comment. I removed it. Thanks
___
*[`pkg/vcdsdk/org.go` line 1 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aJr_R0GNvGb37bDko:-N0aUOK15vxo4CLZ8m7X:b-no32gu) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/org.go#L1)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This vcdsdk package can also contain all RDE management files and resourceset files. Are you planning to do that in a different PR?
</blockquote></details>

The main branch doesn't have the content related to the new schema.
I am planning to include the functions for RDE management when I cherry-pick this commit to vkp branch
___
*[`pkg/vcdsdk/org.go` line 16 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aIqI40yA2Jeo3-u_c:-N0aUcq58Pt0svYgVyT0:bmmh259) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/org.go#L16)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This also needs to take orgName as a param.
How does this work in the case of Sysadmin case. 

</blockquote></details>

As discussed, I have added another member to the OrgManager struct and implemented a fallback to client.ClusterOrgName if orgName supplied is ""
___
*[`pkg/vcdsdk/org.go` line 25 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aJ8910O-E1AGfgkSI:-N0aUlUT1UUwAqb-gsNV:b-w02hn2) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/org.go#L25)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What is ClusterOrgName?
Is this LoggedInOrgName (or) the tenantOrgName?
How does this work in the sysadmin case?
</blockquote></details>

The ClusterOrgName will be the org in which the cluster is present (tenantOrg).
For sysadmin, the clusterOrgName will still be the tenantOrg. The logged in org can be obtained by `client.VCDAuthConfig.UserOrg`
___
*[`pkg/vcdsdk/vapp.go` line 23 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aFPfY-E973HIwvYov:-N0bnfB32qJanmxxLUwq:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/vapp.go#L23)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

vdcManager need to take vdcName as a param at the least.

If you are naming it VDCManager (instead of vAppManager), then there is no need for a separate VMManager.
I suggest referencing VM methods also to VDCManager to keep it simple. 

Both the managers need exactly the same details - client and vdcName. You can check CAPVCD files for reference. Do let me know if there is a need to keep them separate. 
</blockquote></details>

Done.
___
*[`pkg/vcdsdk/vms.go` line 37 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-N0aBd1w8y4RuGCo_wrh:-N0bnnV7BpGbgCnFBf0H:b-98x1vt) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0359150502d1b87a830bc8ebbb03b0fcc2f236ab/pkg/vcdsdk/vms.go#L37)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Client and vAppName are not sufficient to create a VM. VDC details are required as well.
Please take VdcName also as a param and then populate VDC object.

I understand that the current client has a VDC object, but that needs to be used as just a fallback. 

Please add a VDC object (in the struct); it can be populated from the vdcname using the below reference logic. Orgname can be retrieved from the client.VcdAuthConfig. If vdcName is empty then fallback to client.VDC 


```
func (vdc *VdcManager) CacheVdcDetails() error {

	vcdClient, err := vdc.Client.VcdAuthConfig.GetPlainClientFromSecrets()
	if err != nil {
		return fmt.Errorf("unable to get plain client from secrets: [%v]", err)
	}

	org, err := vcdClient.GetOrgByName(vdc.OrgName)
	if err != nil {
		return fmt.Errorf("unable to get org from name [%s]: [%v]", vdc.OrgName, err)
	}

	vdc.Vdc, err = org.GetVDCByName(vdc.VdcName, true)
	if err != nil {
		return fmt.Errorf("unable to get Vdc [%s] from org [%s]: [%v]", vdc.VdcName, vdc.OrgName, err)
	}
	return nil
}
```
</blockquote></details>

I have moved all the functions in vms.go to vapp.go and have used VdcManager as the receiver for all the methods from vms.go. VdcManager is already caching VDC object.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-:-N0bz3b4CHhF0n9Ei6MH:bg7igkv)* status: 4 of 21 files reviewed, 11 unresolved discussions (waiting on @arunmk and @sahithi)

**Review by Anirudh9794 — COMMENTED** [review]
@arunmk sorry, I missed your question here.
yes. I was able to run all the tests successfully.

I felt that CreateLoadBalancer, UpdateLoadBalancer ... are functions which had specific implementations to CPI. So I have moved the RDE operations over to these methods and have separated them out into vcdcpiclient package.

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-:-N0cTQEO0ankB08GESA0:bo79ksd)* status: 4 of 21 files reviewed, 11 unresolved discussions (waiting on @arunmk and @sahithi)

**Review by arunmk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/65#-:-N0cU8Yj1WSCc3NOIMO4:bnfp4nl)* status: 4 of 21 files reviewed, 11 unresolved discussions (waiting on @arunmk and @sahithi)

**Pull request merged**
