### PR TITLE
[VCDA-3047]Update virtual ips for capvcd rde in CPI

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Make sure that RDE updates doesn't cause hard failures in CPI
* Update CAPVCD RDE if the cluster RDE is of type CAPVCD cluster

Testing done:
* Installed ingress and checked if virtual IPs are getting updated in CAPVCD RDE.

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[pkg/util/defined_entity_util.go, line 37 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpmc1_Z9RDNEUdEbi2G:-Mpmc1_Z9RDNEUdEbi2H:bwgrh1k) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L37)):*
> ```Go
> 	if rde.EntityType == CAPVCDEntityTypeID {
> 		virtualIpInterfaces := statusMap["virtualIPs"]
> 		if virtualIpInterfaces == nil {
> ```

minor: this logic could come after this if-else body so that the check isn't repeated in both the CapVCD and native cases

**Comment by ltimothy7** [comment]
___
*[pkg/util/defined_entity_util.go, line 24 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-MpmwZ84CxUknNINGp7W:-MpmwZ84CxUknNINGp7X:b-qqa8ke) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L24)):*
> ```Go
> )
> 
> func GetVirtualIPFromRDE(rde  *swaggerClient.DefinedEntity) ([]string, error) {
> ```

I think `GetVirtualIpsFromRDE` (plural ip) would be clearer

**Review by ltimothy7 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-:-MpmwfKr3bLyhXMcPb9J:b593w57)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[pkg/util/defined_entity_util.go, line 36 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn55Hl6K-Ckfvyhq0M:-Mpn55Hl6K-Ckfvyhq0N:bno6rsh) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L36)):*
> ```
> return nil, fmt.Errorf("entity type %s not supported by CPI", rde.EntityType)
> ```
should this be `=` instead of `:=` since the variable was already declared? Similar for the native case

**Comment by ltimothy7** [comment]
___
*[pkg/vcdclient/gateway.go, line 1147 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn5g9i9BkU3TT28jH-:-Mpn5g9i9BkU3TT28jH0:b-dgg912) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/vcdclient/gateway.go#L1147)):*
> ```Go
> 	virtualIpStrs, err := util.GetVirtualIPFromRDE(&defEnt)
> 	if err != nil {
> 		return nil, "", nil, fmt.Errorf("failed to retrieve Virtual IPs from RDE")
> ```

should print err

**Comment by ltimothy7** [comment]
___
*[pkg/util/defined_entity_util.go, line 64 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn6kpY-jFGpumzpMIM:-Mpn6kpY-jFGpumzpMIN:b5h5zq) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L64)):*
> ```Go
> }
> 
> func UpdateVirtualIPsInRDE(rde *swaggerClient.DefinedEntity, updatedIps []string) (*swaggerClient.DefinedEntity, error) {
> ```

Since this function doesn't actually do the update, I think the function name should be called `ReplaceVirtualIPsInRDE` or something like this

**Comment by ltimothy7** [comment]
___
*[pkg/vcdclient/gateway.go, line 1157 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn7t6M8jG6QOe_1B0H:-Mpn7t6M8jG6QOe_1B0I:b-xpwcj8) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/vcdclient/gateway.go#L1157)):*
> ```Go
> 	defEnt, err := util.UpdateVirtualIPsInRDE(defEnt, updatedIps)
> 	if err != nil {
> 		return nil, fmt.Errorf("failed to update virtual IPs for RDE with ID %s", client.ClusterID)
> ```

should log error here

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[pkg/util/defined_entity_util.go, line 24 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-MpmwZ84CxUknNINGp7W:-Mpn_kUn35t6JzeTxmIa:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L24)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think `GetVirtualIpsFromRDE` (plural ip) would be clearer
</blockquote></details>

Done.
___
*[pkg/util/defined_entity_util.go, line 36 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn55Hl6K-Ckfvyhq0M:-Mpn_tlB8nitLqpji4qC:bt6h0zw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L36)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

> ```
> return nil, fmt.Errorf("entity type %s not supported by CPI", rde.EntityType)
> ```
should this be `=` instead of `:=` since the variable was already declared? Similar for the native case
</blockquote></details>

Thanks for catching this. Done.
___
*[pkg/util/defined_entity_util.go, line 37 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpmc1_Z9RDNEUdEbi2G:-MpnaMGf8BZfnTwHtrTd:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L37)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

minor: this logic could come after this if-else body so that the check isn't repeated in both the CapVCD and native cases
</blockquote></details>

Done.
___
*[pkg/vcdclient/gateway.go, line 1147 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn5g9i9BkU3TT28jH-:-MpnazgwC4r3qVkZt5Zt:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/vcdclient/gateway.go#L1147)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

should print err
</blockquote></details>

Done.
___
*[pkg/vcdclient/gateway.go, line 1157 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn7t6M8jG6QOe_1B0H:-Mpnb7q9DwpQm5UFIKEA:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/vcdclient/gateway.go#L1157)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

should log error here
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[pkg/util/defined_entity_util.go, line 64 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn6kpY-jFGpumzpMIM:-MpncPl92XWkg3B0at0x:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L64)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Since this function doesn't actually do the update, I think the function name should be called `ReplaceVirtualIPsInRDE` or something like this
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-:-MprhoMN0HZ-2RPsWOX7:bg7igkv)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[pkg/util/defined_entity_util.go, line 64 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn6kpY-jFGpumzpMIM:-MprgnmyBUY7tL_vJH9x:b-n0q7wu) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L64)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we add a comment that this method doesn't really update the RDE by making a VCD API call and it is merely a local change in the value of data structure?
For a moment I wondered why we have two methods with a similar name.

we must soon establish a practice of adding docstrings for methods.
___
*[pkg/vcdclient/gateway.go, line 1157 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mprhbf4CTJY--jbHE-r:-Mprhbf53UYTpKdInQFK:bvemccg) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/vcdclient/gateway.go#L1157)):*
> ```Go
> 	defEnt, err := util.UpdateVirtualIPsInRDE(defEnt, updatedIps)
> 	if err != nil {
> 		return nil, fmt.Errorf("failed to update virtual IPs for RDE with ID %s", client.ClusterID)
> ```

Failed to locally edit the RDE with virtual IPs

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[pkg/util/defined_entity_util.go, line 64 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mpn6kpY-jFGpumzpMIM:-MpsCfLjEXr2_GUBGNna:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/util/defined_entity_util.go#L64)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we add a comment that this method doesn't really update the RDE by making a VCD API call and it is merely a local change in the value of data structure?
For a moment I wondered why we have two methods with a similar name.

we must soon establish a practice of adding docstrings for methods.
</blockquote></details>

Done.
___
*[pkg/vcdclient/gateway.go, line 1157 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33#-Mprhbf4CTJY--jbHE-r:-MpsD6l8DKgQAw8Azu2S:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/530ebef1bee13c481423c75f9217bb12846a6c9f/pkg/vcdclient/gateway.go#L1157)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Failed to locally edit the RDE with virtual IPs
</blockquote></details>

Done.

**Pull request merged**
