### PR TITLE
[VKCI-89] Skeleton structure and starter code for automation common code

### PR DESCRIPTION
**Pull request by lzichong**
Initializes VCDClient, gets Kubeconfig, and other RDE helper methods.

Tested against local load balancer test cases and is giving expected results back

Signed-off-by: lzichong <lzichong@vmware.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182)

### CODE REVIEW

**Review by ymo24 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk, @lzichong, and @rliang88)

___
*[`pkg/testingsdk/client.go` line 28 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NIoCcDrAzFBEbtUWCxQ:-NIoCcDs5Bn_tbk1-1_O:b-k6xqkq) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/222265801c4d11c6b207ff7c5565e974199b7a43/pkg/testingsdk/client.go#L28)):*
> ```Go
> 
> type DeployParams struct {
> 	//  TODO: To be determined for K8s Deployment Creation
> ```

type DeployParams struct {
	Name            string
	labels          map[string]string
	volumeParams    VolumeParams
	containerParams ContainerParams
}
type VolumeParams struct {
	volumeName string
	pvcRef     string
	mountPath  string
}

type ContainerParams struct {
	ContainerName  string
	ContainerImage string
	ContainerPort  int32
	Args           []string
}
___
*[`pkg/testingsdk/client.go` line 59 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NIo8s4C9mk3jlgix4Gs:-NIo8s4C9mk3jlgix4Gt:bitb0hy) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/222265801c4d11c6b207ff7c5565e974199b7a43/pkg/testingsdk/client.go#L59)):*
> ```Go
> 
> func (tc *TestClient) GetVCDResourceSet(componentName string) ([]vcdsdk.VCDResource, error) {
> 	vcdResourceSetArrMapping, err := getVcdResourceSetComponentMapFromRDEId(context.TODO(), tc.VcdClient, componentName, tc.ClusterId)
> ```

vcdResourceSetArrMapping might be confusing. Would you please consider vcdResourceSetEntry or vcdResourceSetMap?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @arunmk, @rliang88, and @ymo24)

___
*[`pkg/testingsdk/client.go` line 28 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NIoCcDrAzFBEbtUWCxQ:-NIs-l0WEqoXJV1zcBMl:bkcdk6g) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/222265801c4d11c6b207ff7c5565e974199b7a43/pkg/testingsdk/client.go#L28)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

type DeployParams struct {
	Name            string
	labels          map[string]string
	volumeParams    VolumeParams
	containerParams ContainerParams
}
type VolumeParams struct {
	volumeName string
	pvcRef     string
	mountPath  string
}

type ContainerParams struct {
	ContainerName  string
	ContainerImage string
	ContainerPort  int32
	Args           []string
}
</blockquote></details>

Updated, thanks Yan!

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @arunmk, @rliang88, and @ymo24)

___
*[`pkg/testingsdk/client.go` line 59 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NIo8s4C9mk3jlgix4Gs:-NIs4-Tn-KR6xoPI3NUq:b94jzny) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/222265801c4d11c6b207ff7c5565e974199b7a43/pkg/testingsdk/client.go#L59)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

vcdResourceSetArrMapping might be confusing. Would you please consider vcdResourceSetEntry or vcdResourceSetMap?
</blockquote></details>

Updated, thanks!

**Review by rliang88 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @arunmk, @lzichong, and @ymo24)

___
*[`pkg/testingsdk/client.go` line 78 at r4](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NJ7gZbS-cahWPAjr2Ha:-NJ7gZbS-cahWPAjr2Hb:bkddjuw) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/bc7c01a9207e8008383dc74722881fd57c64e93b/pkg/testingsdk/client.go#L78)):*
> ```Go
> // Returns status.component as map[string]interface{}, this will help us narrow down to specific fields such as nodepools, vcdresources, etc
> // Components: vcdKe, projector, csi, cpi, capvcd
> func (tc *TestClient) GetComponentMapInStatus(ctx context.Context, componentName string) (map[string]interface{}, error) {
> ```

Is there a reason we have this function instead of making the getComponentMapInStatus() in rde_utils public?

**Review by rliang88 — COMMENTED** [review]
shouldn't all of these functions begin with an upper-case letter if we want them to be public?

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-:-NJ7hd1P0qgsgE9XcdOI:b-2283ax)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @arunmk, @lzichong, and @ymo24)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @arunmk, @rliang88, and @ymo24)

___
*[`pkg/testingsdk/client.go` line 78 at r4](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NJ7gZbS-cahWPAjr2Ha:-NJ7iGMH1uejtOZ_FLxN:b4uo6pi) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/bc7c01a9207e8008383dc74722881fd57c64e93b/pkg/testingsdk/client.go#L78)):*
<details><summary><i>Previously, rliang88 (Richard Liang) wrote…</i></summary><blockquote>

Is there a reason we have this function instead of making the getComponentMapInStatus() in rde_utils public?
</blockquote></details>

Updated, thanks! Initially I had wanted to keep it in the test client to reduce amount of params being passed when using it, but it would make more sense in rde_utils

**Comment by lzichong** [comment]
> shouldn't all of these functions begin with an upper-case letter if we want them to be public?
> 
> > _[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-:-NJ7hd1P0qgsgE9XcdOI:b-2283ax)_ status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @arunmk, @lzichong, and @ymo24)

I only wanted to expose a few of them actually, as majority of the exposed functions should come from Yan's PR. So this one ideally should have the initialization of the TestClient to set it up with the associated kubeconfig for clientset. And the primary functions that we should be using from this are: 
1. `GetVCDResourceSet()` (exposed and moved to rde_utils.go)
2. `GetComponentMapInStatus` (exposed and moved to rde_utils.go)
3. `GetClusterName` (exposed in client.go) - this is because there is no way to retrieve the cluster name via `client-go`

The other methods should remain as unexposed as they're more so used as helpers to get VCDResourceSet

**Review by ymo24 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-:-NJBbdRmAF8Ge_PY-Umj:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @arunmk and @rliang88)

**Review by arunmk — APPROVED** [review]
:lgtm: with a few basic comments.

At some point we should discuss how to make this work across RDE versions. It is not required for this commit though.

> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-:-NLUq9ucCF4mPyk-2SIy:b3bzufn)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @lzichong, @rliang88, and @ymo24)

___
*[`pkg/testingsdk/rde_utils.go` line 20 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUoBKa55idY15sAlVy:-NLUoBKa55idY15sAlVz:bg78375) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/rde_utils.go#L20)):*
> ```Go
> // Returns status.component as map[string]interface{}, this will help us narrow down to specific fields such as nodepools, vcdresources, etc
> // Components: vcdKe, projector, csi, cpi, capvcd
> func GetComponentMapInStatus(ctx context.Context, client *vcdsdk.Client, clusterId, componentName string) (map[string]interface{}, error) {
> ```

There may be need of a version in the future here. We won't need to block this commit for it though.

However could you add a comment saying that these functions are not resilient to RDE version changes.
___
*[`pkg/testingsdk/rde_utils.go` line 26 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUpLiN7dS_5NnBvOfs:-NLUpLiN7dS_5NnBvOft:b-fdhcmz) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/rde_utils.go#L26)):*
> ```Go
> 	}
> 
> 	rde, _, _, err := client.APIClient.DefinedEntityApi.GetDefinedEntity(ctx, clusterId, org.Org.ID)
> ```

we could potentially use `getRdeById` here
___
*[`pkg/testingsdk/client.go` line 52 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUmQ5p4KGYxFKsMaP8:-NLUmQ5p4KGYxFKsMaP9:b-3i71md) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/client.go#L52)):*
> ```Go
> 	}
> 
> 	kubeConfig, err := getKubeconfigFromRDEId(context.TODO(), client, clusterId)
> ```

I think this can be an exposed function but it is fine for now.
___
*[`pkg/testingsdk/client.go` line 71 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUmjuLEvx8bcy-Y1JM:-NLUmjuLEvx8bcy-Y1JN:ba652ls) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/client.go#L71)):*
> ```Go
> 	rde, err := getRdeById(ctx, tc.VcdClient, clusterId)
> 	if err != nil {
> 		return "", fmt.Errorf("error retrieving cluster name by clusterId [%s]: [%v]", clusterId, err)
> ```

error should be 'unable to get RDE'

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @arunmk, @rliang88, and @ymo24)

___
*[`pkg/testingsdk/rde_utils.go` line 20 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUoBKa55idY15sAlVy:-NLX0cu52aoztBUdGoED:b-48p3zv) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/rde_utils.go#L20)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

There may be need of a version in the future here. We won't need to block this commit for it though.

However could you add a comment saying that these functions are not resilient to RDE version changes.
</blockquote></details>

Added at the top as a TODO, thanks Arun!
___
*[`pkg/testingsdk/rde_utils.go` line 26 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUpLiN7dS_5NnBvOfs:-NLX0bMS4u_nt491eoRW:b-k5zjvr) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/rde_utils.go#L26)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

we could potentially use `getRdeById` here
</blockquote></details>

Updated, thanks for the catch!
___
*[`pkg/testingsdk/client.go` line 52 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUmQ5p4KGYxFKsMaP8:-NLX0gdb-iPI-yeIpkHN:b-d4bm82) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/client.go#L52)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think this can be an exposed function but it is fine for now.
</blockquote></details>

I have exposed it for now as common core changes could be tedious if updating other projects after changes, thanks Arun!
___
*[`pkg/testingsdk/client.go` line 71 at r8](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/182#-NLUmjuLEvx8bcy-Y1JM:-NLX0fMb63ulyQl5nobh:b94jzny) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/95a798b3a9b60f3cf1ce9d685257f061dba566df/pkg/testingsdk/client.go#L71)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

error should be 'unable to get RDE'
</blockquote></details>

Updated, thanks!

**Pull request merged**
