### PR TITLE
VCDA-2922: Allow users from different ORGs to access clusters in

### PR DESCRIPTION
**Pull request by arunmk**
Allow users from different ORGs to access clusters in different ORGs when using the userid/password method.
Also use a different VM search mechanism in order to find VMs accurately and initialize them with provider ID.

This requires a change in CSE to also pass the Cluster Name. I have named this parameter as the VAPP, since that will be clear in cases of non-CSE clusters.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-:-MkY2xHCBIBTv_PItpYq:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[pkg/vcdclient/auth.go, line 66 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-MkY20f88PSLl7WweeOy:-MkY20f88PSLl7WweeOz:bj0vkpk) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6e044f4e1a818b18943c17f51c293ec80307921b/pkg/vcdclient/auth.go#L66)):*
> ```Go
> 			return nil, nil, fmt.Errorf("failed to set authorization header: [%v]", err)
> 		}
> 		vcdClient.Client.IsSysAdmin, err = isAdminUser(vcdClient)
> ```

I think this check will be redundant now since govcd will now set IsSysAdmin based on UserOrg.
___
*[pkg/vcdclient/client.go, line 86 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-MkY2Y3r1_4LKHVfsfkm:-MkY2Y3s8BlxbqFUihtK:bg38k79) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6e044f4e1a818b18943c17f51c293ec80307921b/pkg/vcdclient/client.go#L86)):*
> ```Go
> 
> 	// Fill up the vdc field again so that clients can reuse legacy API
> 	org, err := client.vcdClient.GetOrgByNameOrId(client.ClusterOrgName)
> ```

Sorry, missed this part  before

**Comment by Anirudh9794** [comment]
___
*[pkg/vcdclient/vms.go, line 27 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-MkYKO1qC74vbKpxLNSS:-MkYKO1qC74vbKpxLNST:bmv1qa9) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6e044f4e1a818b18943c17f51c293ec80307921b/pkg/vcdclient/vms.go#L27)):*
> ```Go
> 	}
> 
> 	if err := client.RefreshBearerToken(); err != nil {
> ```

Won't the client be refreshed in the top level functions itself?

**Comment by Anirudh9794** [comment]
___
*[pkg/vcdclient/auth.go, line 66 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-MkY20f88PSLl7WweeOy:-MkYPnrT4Dyif8uxv0Tf:b90glef) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6e044f4e1a818b18943c17f51c293ec80307921b/pkg/vcdclient/auth.go#L66)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this check will be redundant now since govcd will now set IsSysAdmin based on UserOrg.
</blockquote></details>

sorry, this is still required.

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[pkg/vcdclient/auth.go, line 66 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-MkY20f88PSLl7WweeOy:-MkYjsPND4ho91EXC5Hv:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6e044f4e1a818b18943c17f51c293ec80307921b/pkg/vcdclient/auth.go#L66)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

sorry, this is still required.
</blockquote></details>

Done.
___
*[pkg/vcdclient/client.go, line 86 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-MkY2Y3r1_4LKHVfsfkm:-MkYjtVa0dpRF6cI4Imv:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6e044f4e1a818b18943c17f51c293ec80307921b/pkg/vcdclient/client.go#L86)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Sorry, missed this part  before 
</blockquote></details>

Done.
___
*[pkg/vcdclient/vms.go, line 27 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/17#-MkYKO1qC74vbKpxLNSS:-MkYkur8Cq8qMnATKJgm:b3px6ho) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6e044f4e1a818b18943c17f51c293ec80307921b/pkg/vcdclient/vms.go#L27)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Won't the client be refreshed in the top level functions itself?
</blockquote></details>

Thanks, changed.

**Pull request merged**
