### PR TITLE
[VKCI-121] Package CPI CRS file in container each time images are made

### PR DESCRIPTION
**Pull request by lzichong**
Signed-off-by: lzichong <lzichong@vmware.com>

* Testings:
  * ran `make dev` which gave `__REGISTRY__/cloud-provider-for-cloud-director:version.gitSha`
    * ex) `image: __REGISTRY__/cloud-provider-for-cloud-director:lzichong-dummy.cb3a613`
  * ran `make prod` which updated the `image: __REGISTRY__/cloud-provider-for-cloud-director:version`
  * Verified the container in TKG VM by extracting the container
  * Verified on local machine that yaml file is in container

To pull CRS dev container: `pull __REGISTRY__/cpi-crs-airgapped:d1e7a9a`
To pull CRS prod container: `pull __REGISTRY__/cpi-crs-airgapped:1.3.0`

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abaruni, @arunmk, and @rocknes)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-:-NN0NOVEAIfRK0ZgA7ne:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni, @arunmk, and @lzichong)

___
*[`artifacts/cloud-director-ccm-crs-airgap.yaml` line 157 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-NN0Mu7P7uxrzLyzDqUV:-NN0Mu7P7uxrzLyzDqUW:b-3tw0ri) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/800d5aadf9f9b06e411a002bd9889f4c746f2c15/artifacts/cloud-director-ccm-crs-airgap.yaml#L157)):*
> ```YAML
>       containers:
>         - name: vmware-cloud-director-ccm
>           image: __REGISTRY__/cloud-provider-for-cloud-director:lzichong-dummy.cb3a613
> ```

Are we getting rid of the dummy string before packing it in the container?
Or should this be a template variable?

On a second thought, should this file be even checked in? Just the yaml template is enough right?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni, @arunmk, and @rocknes)

___
*[`artifacts/cloud-director-ccm-crs-airgap.yaml` line 157 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-NN0Mu7P7uxrzLyzDqUV:-NN2wNIECSkbaMfhqEJv:bgof09h) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/800d5aadf9f9b06e411a002bd9889f4c746f2c15/artifacts/cloud-director-ccm-crs-airgap.yaml#L157)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Are we getting rid of the dummy string before packing it in the container?
Or should this be a template variable?

On a second thought, should this file be even checked in? Just the yaml template is enough right?
</blockquote></details>

Yes the dummy string variable will be removed for the official CRS files as by default it gets replaced by what's in release/version + gitcommit, this was more of a testing to verify the change had gone through. 

But I agree we can actually skip committing this file, yaml template should be enough. Each image build this file gets locally generated. I'll remove this file from the PR, thanks Aritra!

**Review by abaruni — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @rocknes)

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arunmk)

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @lzichong)

___
*[`artifacts/Dockerfile` line 2 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-NN8qVYv8A4clT5CNczs:-NN8qVYv8A4clT5CNczt:blvei3g) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d8b6baeac0041c2b1f5a780a194853e96fd03cfe/artifacts/Dockerfile#L2)):*
> ```Dockerfile
> FROM scratch
> COPY /artifacts/cloud-director-ccm-crs-airgap.yaml /src/artifact/
> ```

We need to copy the template file and not the yaml

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @lzichong)

___
*[`artifacts/Dockerfile` line 2 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-NN8qVYv8A4clT5CNczs:-NN8qhDqBW7xHatWssEx:b-em4f0q) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d8b6baeac0041c2b1f5a780a194853e96fd03cfe/artifacts/Dockerfile#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We need to copy the template file and not the yaml
</blockquote></details>

btw the version/git-sha needs to be plugged in though :-)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @abaruni, @arunmk, @rocknes, and @sakthisunda)

___
*[`artifacts/Dockerfile` line 2 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-NN8qVYv8A4clT5CNczs:-NN91BR5CKMDWAqINAg3:b-11v8s) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d8b6baeac0041c2b1f5a780a194853e96fd03cfe/artifacts/Dockerfile#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

btw the version/git-sha needs to be plugged in though :-)
</blockquote></details>

Updated to .template file, and in artifacts template file, image would look like:

prod: `__REGISTRY__/cloud-provider-for-cloud-director:1.3.0`
dev: `__REGISTRY__/cloud-provider-for-cloud-director:1.3.0.2d7bdc4`

Thanks for the correction!

**Review by rocknes — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-:-NN92dlKArXPSVolo-Xu:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @abaruni, @arunmk, and @sakthisunda)

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/217#-:-NN97O0G7DvTmi2jpkV1:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @abaruni, @arunmk, and @sakthisunda)

**Pull request merged**
