### PR TITLE
[VCDA-3669] Remove dependency of CPI's config from vcdsdk

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Create a structure to parse a test config to execute system tests in vcdsdk and remove dependency on CPI's config

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76)

### CODE REVIEW

**Review by ymo24 — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lzichong and @sahithi)

**Review by lzichong — APPROVED** [review]
> Reviewed 9 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[`pkg/vcdsdk/common_system_test.go` line 84 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76#-N1iy1L2Dx1k05xJGKYB:-N1iy1L2Dx1k05xJGKYC:b-24g9zn) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0f46a852b5b0da3d6c8539a9ac82d655af9a6801/pkg/vcdsdk/common_system_test.go#L84)):*
> ```Go
> 
> // getTestVCDClient returns a client created using the file testdata/vcd_info.yaml
> func getTestVCDClient(vcdConfig *VcdConfig, inputMap map[string]interface{}) (*Client, error) {
> ```

I think we should make a copy of the vcdConfig here and return client from modified copy instead of modifying the config directly from param since if we modify a field for one test case it may carry over to another test case when we chain getTestVCDClient() calls right?



_Code quote:_
```Go
func getTestVCDClient(vcdConfig *VcdConfig, inputMap map[string]interface{}) (*Client, error) {
	insecure := true
	getVdcClient := false
	if inputMap != nil {
```

**Comment by Anirudh9794** [comment]
*[`pkg/vcdsdk/common_system_test.go` line 84 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76#-N1iy1L2Dx1k05xJGKYB:-N1jBNKe-HbMzmwoOBtt:b-ifrwr8) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0f46a852b5b0da3d6c8539a9ac82d655af9a6801/pkg/vcdsdk/common_system_test.go#L84)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

I think we should make a copy of the vcdConfig here and return client from modified copy instead of modifying the config directly from param since if we modify a field for one test case it may carry over to another test case when we chain getTestVCDClient() calls right?
</blockquote></details>

Yes, You are right, I made a copy to modify the config.
Thanks Yan.

**Review by lzichong — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @lzichong, @sahithi, and @ymo24)

___
*[`pkg/vcdsdk/common_system_test.go` line 84 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76#-N1iy1L2Dx1k05xJGKYB:-N1k1wj83SZ0JcZUXEJR:b3b3k86) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/0f46a852b5b0da3d6c8539a9ac82d655af9a6801/pkg/vcdsdk/common_system_test.go#L84)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Yes, You are right, I made a copy to modify the config.
Thanks Yan.
</blockquote></details>

:lgtm:, thanks Aniruddh!

**Review by sahithi — APPROVED** [review]
:lgtm: Is there a task tracking similar changes in CAPVCD? If not, please create one.

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76#-:-N1ohZZ04AQpzyYYbMTq:bajoz2x)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @lzichong, and @ymo24)

**Review by Anirudh9794 — COMMENTED** [review]
i will update CPI dependency in CAPVCD. I think  that should solve the config dependency in CAPVCD

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/76#-:-N1oq3I-ENuk7bYHnwuD:b5fbpyo)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @lzichong, and @ymo24)

**Pull request merged**
