### PR TITLE
[VKCI-70] Fix to ensure VCD resources are cleaned up after deleting LB service even if LB failed during deployment

### PR DESCRIPTION
**Pull request by lzichong**
* Testings done:
Attempt LB deployment with invalid configurations which causes the load balancer to never come up, and then performing a delete and saw the VCD resources get cleaned up.

Signed-off-by: lzichong <lzichong@vmware.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179)

### CODE REVIEW

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/ccm/loadbalancer.go` line 303 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-NIhYOUt2UaN9t0OupiS:-NIi6tuS4sLEeG0eq_Ye:bvpr1mz) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/45edd0b3350f53c7632945dd402516fcb27cc346/pkg/ccm/loadbalancer.go#L303)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Not related to this PR but can we update the error message here? it should be something like "unable to get load balancer information for the service <name>: <error>"
</blockquote></details>

Updated, thanks Aniruddh!
___
*[`pkg/ccm/loadbalancer.go` line 357 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-NIh_xjMC2pjRDSeSdJX:-NIi6vtQ2FZtveZv9iX6:b-6s7aot) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/45edd0b3350f53c7632945dd402516fcb27cc346/pkg/ccm/loadbalancer.go#L357)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

will this error appear in the stack trace? If not, we should log the error here.
</blockquote></details>

Added klog.Errorf() here, thanks!
___
*[`pkg/ccm/loadbalancer.go` line 699 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-NIhbzet02k_cj3m3Rcs:-NIi6ykM8I0w5K6addE4:bgijz2q) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/45edd0b3350f53c7632945dd402516fcb27cc346/pkg/ccm/loadbalancer.go#L699)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Won't GetVirtualService() return an error if virtual service is not found?
If so, then the code after the `if vsSummary != nil` wont get executed right? Because there can be only 2 cases - The virtual service is present / absent (we are returning in both the cases)
</blockquote></details>

In GetVirtualService() it does not return an error if vsSummary is not found, it returns nil for both error and vsSummary if len(virtualServiceResult) != 1. It seems we will only return an error if there was an actual error in making the API request. 
___
*[`pkg/ccm/loadbalancer.go` line 702 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-NIhapsw-jjWeWYCkEUW:-NIi93cs6PGCw3kBBlY9:b-qlqbut) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/45edd0b3350f53c7632945dd402516fcb27cc346/pkg/ccm/loadbalancer.go#L702)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

vsSummary will be nil even when there are more than one virtual service. I am not sure how this edge case should be handled.
If we don't handle it, we should change the message logged.
</blockquote></details>

Can you clarify on this? When there are multiple virtual service they all should have unique names right? And since our API is filtering out VS by name, I think we should only be expecting 1 VS each time right?
___
*[`pkg/ccm/loadbalancer.go` line 707 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-NIhd8nbEQnP_lUV4Deg:-NIi84RtD1WXN9oFPwYC:b9f3hc4) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/45edd0b3350f53c7632945dd402516fcb27cc346/pkg/ccm/loadbalancer.go#L707)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I have the same question about execution as before for this block as well
</blockquote></details>

lbPool does return an error if it's nil, I will add a govcd.ErrorEntityNotFound && err != nil to the check, thanks!

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/ccm/loadbalancer.go` line 702 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-NIhapsw-jjWeWYCkEUW:-NIimYGzEZ_QsQ6Y7bZA:b-cn3xv5) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/45edd0b3350f53c7632945dd402516fcb27cc346/pkg/ccm/loadbalancer.go#L702)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Can you clarify on this? When there are multiple virtual service they all should have unique names right? And since our API is filtering out VS by name, I think we should only be expecting 1 VS each time right?
</blockquote></details>

Following up: I have checked with Aniruddh over Slack, we are only expecting 1 virtual service of same name as VCD doesn't allow duplicate VS names, so comments has been added to the function for clarity
___
*[`pkg/ccm/loadbalancer.go` line 722 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-NIhdqHB7HcWxr76WmKY:-NIimUFb2NJg9Y7cGW6Q:bvpr1mz) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/45edd0b3350f53c7632945dd402516fcb27cc346/pkg/ccm/loadbalancer.go#L722)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

We should also check for app port profile.
</blockquote></details>

Updated, thanks Aniruddh!

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-:-NInxAq6EpU9Q1wzq79o:bg7igkv)* status: all files reviewed, 6 unresolved discussions (waiting on @arunmk)

**Review by arunmk — APPROVED** [review]
:lgtm: after Aniruddha's comments are answered.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179#-:-NJ8RwhD5q2m7__2Zu40:b-pclcgo)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794)

**Pull request merged**
